### PR TITLE
[pgm_learner] add pgm_learner package

### PR DESCRIPTION
**Pull request by furushchev**

### CODE REVIEW

**Comment by furushchev** [comment]
travis failed

```
<?xml version="1.0" encoding="utf-8"?>
<testsuite errors="2" failures="0" name="unittest.suite.TestSuite" tests="3" time="2.437">
  <testcase classname="__main__.TestDiscreteBNLearnerNode" name="test_param_estimation" time="0.0156">
    <error type="ServiceException">service [/pgm_learner/discrete/parameter_estimation] unavailable
  File "/usr/lib/python2.7/unittest/case.py", line 327, in run
    testMethod()
  File "/home/travis/ros/ws_jsk_3rdparty/src/jsk_3rdparty/pgm_learner/test/test_discrete_bn.py", line 56, in test_param_estimation
    self.assertEqual(len(self.param_estimate(req).nodes), 5)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 435, in __call__
    return self.call(*args, **kwds)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 495, in call
    service_uri = self._get_service_uri(request)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 463, in _get_service_uri
    raise ServiceException("service [%s] unavailable"%self.resolved_name)
    </error>
  </testcase>
  <testcase classname="__main__.TestDiscreteBNLearnerNode" name="test_query" time="0.0028">
    <error type="ServiceException">service [/pgm_learner/discrete/query] unavailable
  File "/usr/lib/python2.7/unittest/case.py", line 327, in run
    testMethod()
  File "/home/travis/ros/ws_jsk_3rdparty/src/jsk_3rdparty/pgm_learner/test/test_discrete_bn.py", line 65, in test_query
    res = self.query(req)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 435, in __call__
    return self.call(*args, **kwds)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 495, in call
    service_uri = self._get_service_uri(request)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 463, in _get_service_uri
    raise ServiceException("service [%s] unavailable"%self.resolved_name)
    </error>
  </testcase>
  <testcase classname="__main__.TestDiscreteBNLearnerNode" name="test_structure_estimation" time="2.4188"></testcase>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
```

I don't know why service is not advertised...
on my local machine `catkin run_tests pgm_learner` passes.

**Comment by furushchev** [comment]
test is aborted

```

**Comment by furushchev** [comment]
restarted travis

**Comment by k-okada** [comment]
this PR was not OK. 
https://github.com/jsk-ros-pkg/jsk_3rdparty/pull/40

**Pull request merged**
