### PR TITLE
[libcmt] add git depend in package.xml

### PR DESCRIPTION
**Pull request by aginika**
From https://github.com/jsk-ros-pkg/jsk_3rdparty/pull/8#issuecomment-138175058

### CODE REVIEW

**Comment by garaemon** [comment]
2.0.6 has been released

**Comment by garaemon** [comment]
Still fails
http://www.ros.org/debbuild/hydro.html

**Comment by garaemon** [comment]
```
- The C compiler identification is GNU
-- The CXX compiler identification is GNU
-- Check for working C compiler: /usr/lib/ccache/gcc
-- Check for working C compiler: /usr/lib/ccache/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/lib/ccache/c++
-- Check for working CXX compiler: /usr/lib/ccache/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
CMake Error at CMakeLists.txt:4 (find_package):
  Could not find module FindOpenCV.cmake or a configuration file for package
  OpenCV.

  Adjust CMAKE_MODULE_PATH to find FindOpenCV.cmake or set OpenCV_DIR to the
  directory containing a CMake configuration file for OpenCV.  The file will
  have one of the following names:

    OpenCVConfig.cmake
    opencv-config.cmake
```

**Comment by k-okada** [comment]
@aginika, you have to add all software required to compile this library to
package.xml, denbild process state from bare Ubuntu emvironment and install
software from package.xml, then compile libraries.

2015年9月11日金曜日、Ryohei Ueda<notifications@github.com>さんは書きました:

> - The C compiler identification is GNU
> -- The CXX compiler identification is GNU
> -- Check for working C compiler: /usr/lib/ccache/gcc
> -- Check for working C compiler: /usr/lib/ccache/gcc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Check for working CXX compiler: /usr/lib/ccache/c++
> -- Check for working CXX compiler: /usr/lib/ccache/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> CMake Error at CMakeLists.txt:4 (find_package):
>   Could not find module FindOpenCV.cmake or a configuration file for package
>   OpenCV.
>
>   Adjust CMAKE_MODULE_PATH to find FindOpenCV.cmake or set OpenCV_DIR to the
>   directory containing a CMake configuration file for OpenCV.  The file will
>   have one of the following names:
>
>     OpenCVConfig.cmake
>     opencv-config.cmake
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsk-ros-pkg/jsk_3rdparty/pull/20#issuecomment-139528391>
> .
>


-- 
--
◉ Kei Okada

**Pull request merged**
