### PR TITLE
[Do not merge] Testing build of bayesian_belief_networks and collada_urdf_jsk_patch

### PR DESCRIPTION
**Pull request by mqcmd196**
Fail building `collada_urdf_jsk_patch` in my machine and fetch.
The result of `catkin b -v`
```
Starting   >> collada_urdf_jsk_patch:make                                                                                                                                                                         
Subprocess  > collada_urdf_jsk_patch:make `cd /tmp/test/build/collada_urdf_jsk_patch; catkin build --get-env collada_urdf_jsk_patch | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -`                 
__________________________________________________________________________________________________________________________________________________________________________________________________________________
Errors     << collada_urdf_jsk_patch:make /tmp/test/logs/collada_urdf_jsk_patch/build.make.002.log                                                                                                                
/usr/bin/cmake -H/tmp/test/src/jsk_3rdparty/jsk_ros_patch/collada_urdf_jsk_patch -B/tmp/test/build/collada_urdf_jsk_patch --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /tmp/test/build/collada_urdf_jsk_patch/CMakeFiles /tmp/test/build/collada_urdf_jsk_patch/CMakeFiles/progress.marks
/usr/bin/make -f CMakeFiles/Makefile2 all
make[1]: ディレクトリ '/tmp/test/build/collada_urdf_jsk_patch' に入ります
/usr/bin/make -f CMakeFiles/urdf_to_collada.dir/build.make CMakeFiles/urdf_to_collada.dir/depend
make[2]: ディレクトリ '/tmp/test/build/collada_urdf_jsk_patch' に入ります
cd /tmp/test/build/collada_urdf_jsk_patch && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /tmp/test/src/jsk_3rdparty/jsk_ros_patch/collada_urdf_jsk_patch /tmp/test/src/jsk_3rdparty/jsk_ros_patch/collada_urdf_jsk_patch /tmp/test/build/collada_urdf_jsk_patch /tmp/test/build/collada_urdf_jsk_patch /tmp/test/build/collada_urdf_jsk_patch/CMakeFiles/urdf_to_collada.dir/DependInfo.cmake --color=
make[2]: ディレクトリ '/tmp/test/build/collada_urdf_jsk_patch' から出ます
/usr/bin/make -f CMakeFiles/urdf_to_collada.dir/build.make CMakeFiles/urdf_to_collada.dir/build
make[2]: ディレクトリ '/tmp/test/build/collada_urdf_jsk_patch' に入ります
[100%] Generating /tmp/test/devel/.private/collada_urdf_jsk_patch/lib/collada_urdf_jsk_patch/urdf_to_collada
cmake -E chdir /tmp/test/build/collada_urdf_jsk_patch make -f /tmp/test/src/jsk_3rdparty/jsk_ros_patch/collada_urdf_jsk_patch/Makefile PKG_CONFIG_PATH=/tmp/test/devel/.private/collada_urdf_jsk_patch/lib/pkgconfig:/tmp/test/devel/.private/collada_urdf_jsk_patch/lib/pkgconfig:/tmp/test/devel/lib/pkgconfig:/opt/ros/melodic/lib/pkgconfig PATCH_DIR=/tmp/test/src/jsk_3rdparty/jsk_ros_patch/collada_urdf_jsk_patch SOURCE_DISTRO=923c5d33bd245e82134e8ae02e4c9d379e80eb27 GIT_REPO=collada_urdf CXXFLAGS=-std=gnu++11
make[3]: ディレクトリ '/tmp/test/build/collada_urdf_jsk_patch' に入ります
make[3]: 警告: jobserver が利用不可: 今回は -j1 を使います. 親 make ルールに `+' を追加しましょう.
mkdir -p build/robot_model/src
mkdir -p build
if [ ! -f /tmp/test/src/jsk_3rdparty/jsk_ros_patch/collada_urdf_jsk_patch/robot_model.923c.md5sum ]; then echo "Error: Couldn't find md5sum file /tmp/test/src/jsk_3rdparty/jsk_ros_patch/collada_urdf_jsk_patch/robot_model.923c.md5sum" && false; fi
/opt/ros/melodic/share/ros/core/rosbuild/bin/download_checkmd5.py https://github.com/ros/collada_urdf/archive/923c5d33bd245e82134e8ae02e4c9d379e80eb27.zip build/robot_model.zip `awk {'print $1'} /tmp/test/src/jsk_3rdparty/jsk_ros_patch/collada_urdf_jsk_patch/robot_model.923c.md5sum`
[rosbuild] Checking md5sum on build/robot_model.zip
[rosbuild] WARNING: md5sum mismatch (f465d2decf50bc1712f2a1d39feb91cf != 21e492f83de3df9f7399bf57ab254d1d); re-downloading file build/robot_model.zip
[rosbuild] ERROR: md5sum mismatch (f465d2decf50bc1712f2a1d39feb91cf != 21e492f83de3df9f7399bf57ab254d1d) on build/robot_model.zip; aborting
/opt/ros/melodic/share/mk/download_unpack_build.mk:37: recipe for target 'build/robot_model/src/unpacked' failed
make[3]: ディレクトリ '/tmp/test/build/collada_urdf_jsk_patch' から出ます
make[3]: *** [build/robot_model/src/unpacked] Error 1
CMakeFiles/urdf_to_collada.dir/build.make:60: recipe for target '/tmp/test/devel/.private/collada_urdf_jsk_patch/lib/collada_urdf_jsk_patch/urdf_to_collada' failed
make[2]: ディレクトリ '/tmp/test/build/collada_urdf_jsk_patch' から出ます
make[2]: *** [/tmp/test/devel/.private/collada_urdf_jsk_patch/lib/collada_urdf_jsk_patch/urdf_to_collada] Error 2
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/urdf_to_collada.dir/all' failed
make[1]: ディレクトリ '/tmp/test/build/collada_urdf_jsk_patch' から出ます
make[1]: *** [CMakeFiles/urdf_to_collada.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
cd /tmp/test/build/collada_urdf_jsk_patch; catkin build --get-env collada_urdf_jsk_patch | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -
..................................................................................................................................................................................................................
Failed     << collada_urdf_jsk_patch:make           [ Exited with code 2 ]                                                                                                                                        
Failed    <<< collada_urdf_jsk_patch                [ 0.7 seconds ]                                                                                                                                               
[build] Summary: 1 of 2 packages succeeded.                                                                                                                                                                       
[build]   Ignored:   30 packages were skipped or are blacklisted.                                                                                                                                                 
[build]   Warnings:  None.                                                                                                                                                                                        
[build]   Abandoned: None.                                                                                                                                                                                        
[build]   Failed:    1 packages failed.                                                                                                                                                                           
[build] Runtime: 0.9 seconds total. 
```
I want to test in travis

### CODE REVIEW

**Comment by mqcmd196** [comment]
Same thing happens in `bayesian_belief_networks`
```
Errors     << bayesian_belief_networks:make /tmp/test/logs/bayesian_belief_networks/build.make.002.log                                                                                                            
/usr/bin/cmake -H/tmp/test/src/jsk_3rdparty/bayesian_belief_networks -B/tmp/test/build/bayesian_belief_networks --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /tmp/test/build/bayesian_belief_networks/CMakeFiles /tmp/test/build/bayesian_belief_networks/CMakeFiles/progress.marks
/usr/bin/make -f CMakeFiles/Makefile2 all
make[1]: ディレクトリ '/tmp/test/build/bayesian_belief_networks' に入ります
/usr/bin/make -f CMakeFiles/python_baysian_belief_networks_download.dir/build.make CMakeFiles/python_baysian_belief_networks_download.dir/depend
/usr/bin/make -f CMakeFiles/_bayesian_belief_networks_generate_messages_check_deps_Observation.dir/build.make CMakeFiles/_bayesian_belief_networks_generate_messages_check_deps_Observation.dir/depend
/usr/bin/make -f CMakeFiles/_bayesian_belief_networks_generate_messages_check_deps_Result.dir/build.make CMakeFiles/_bayesian_belief_networks_generate_messages_check_deps_Result.dir/depend
/usr/bin/make -f CMakeFiles/std_msgs_generate_messages_py.dir/build.make CMakeFiles/std_msgs_generate_messages_py.dir/depend
/usr/bin/make -f CMakeFiles/_bayesian_belief_networks_generate_messages_check_deps_Query.dir/build.make CMakeFiles/_bayesian_belief_networks_generate_messages_check_deps_Query.dir/depend
/usr/bin/make -f CMakeFiles/std_msgs_generate_messages_lisp.dir/build.make CMakeFiles/std_msgs_generate_messages_lisp.dir/depend
make[2]: ディレクトリ '/tmp/test/build/bayesian_belief_networks' に入ります
cd /tmp/test/build/bayesian_belief_networks && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /tmp/test/src/jsk_3rdparty/bayesian_belief_networks /tmp/test/src/jsk_3rdparty/bayesian_belief_networks /tmp/test/build/bayesian_belief_networks /tmp/test/build/bayesian_belief_networks /tmp/test/build/bayesian_belief_networks/CMakeFiles/_bayesian_belief_networks_generate_messages_check_deps_Observation.dir/DependInfo.cmake --color=
make[2]: ディレクトリ '/tmp/test/build/bayesian_belief_networks' に入ります
cd /tmp/test/build/bayesian_belief_networks && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /tmp/test/src/jsk_3rdparty/bayesian_belief_networks /tmp/test/src/jsk_3rdparty/bayesian_belief_networks /tmp/test/build/bayesian_belief_networks /tmp/test/build/bayesian_belief_networks /tmp/test/build/bayesian_belief_networks/CMakeFiles/python_baysian_belief_networks_download.dir/DependInfo.cmake --color=
make[2]: ディレクトリ '/tmp/test/build/bayesian_belief_networks' に入ります
cd /tmp/test/build/bayesian_belief_networks && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /tmp/test/src/jsk_3rdparty/bayesian_belief_networks /tmp/test/src/jsk_3rdparty/bayesian_belief_networks /tmp/test/build/bayesian_belief_networks /tmp/test/build/bayesian_belief_networks /tmp/test/build/bayesian_belief_networks/CMakeFiles/std_msgs_generate_messages_py.dir/DependInfo.cmake --color=
make[2]: ディレクトリ '/tmp/test/build/bayesian_belief_networks' に入ります
make[2]: ディレクトリ '/tmp/test/build/bayesian_belief_networks' に入ります
cd /tmp/test/build/bayesian_belief_networks && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /tmp/test/src/jsk_3rdparty/bayesian_belief_networks /tmp/test/src/jsk_3rdparty/bayesian_belief_networks /tmp/test/build/bayesian_belief_networks /tmp/test/build/bayesian_belief_networks /tmp/test/build/bayesian_belief_networks/CMakeFiles/std_msgs_generate_messages_lisp.dir/DependInfo.cmake --color=
cd /tmp/test/build/bayesian_belief_networks && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /tmp/test/src/jsk_3rdparty/bayesian_belief_networks /tmp/test/src/jsk_3rdparty/bayesian_belief_networks /tmp/test/build/bayesian_belief_networks /tmp/test/build/bayesian_belief_networks /tmp/test/build/bayesian_belief_networks/CMakeFiles/_bayesian_belief_networks_generate_messages_check_deps_Query.dir/DependInfo.cmake --color=
make[2]: ディレクトリ '/tmp/test/build/bayesian_belief_networks' に入ります
cd /tmp/test/build/bayesian_belief_networks && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /tmp/test/src/jsk_3rdparty/bayesian_belief_networks /tmp/test/src/jsk_3rdparty/bayesian_belief_networks /tmp/test/build/bayesian_belief_networks /tmp/test/build/bayesian_belief_networks /tmp/test/build/bayesian_belief_networks/CMakeFiles/_bayesian_belief_networks_generate_messages_check_deps_Result.dir/DependInfo.cmake --color=
make[2]: ディレクトリ '/tmp/test/build/bayesian_belief_networks' から出ます
make[2]: ディレクトリ '/tmp/test/build/bayesian_belief_networks' から出ます
make[2]: ディレクトリ '/tmp/test/build/bayesian_belief_networks' から出ます
/usr/bin/make -f CMakeFiles/python_baysian_belief_networks_download.dir/build.make CMakeFiles/python_baysian_belief_networks_download.dir/build
/usr/bin/make -f CMakeFiles/_bayesian_belief_networks_generate_messages_check_deps_Observation.dir/build.make CMakeFiles/_bayesian_belief_networks_generate_messages_check_deps_Observation.dir/build
/usr/bin/make -f CMakeFiles/std_msgs_generate_messages_lisp.dir/build.make CMakeFiles/std_msgs_generate_messages_lisp.dir/build
make[2]: ディレクトリ '/tmp/test/build/bayesian_belief_networks' から出ます
make[2]: ディレクトリ '/tmp/test/build/bayesian_belief_networks' から出ます
/usr/bin/make -f CMakeFiles/_bayesian_belief_networks_generate_messages_check_deps_Result.dir/build.make CMakeFiles/_bayesian_belief_networks_generate_messages_check_deps_Result.dir/build
/usr/bin/make -f CMakeFiles/std_msgs_generate_messages_py.dir/build.make CMakeFiles/std_msgs_generate_messages_py.dir/build
make[2]: ディレクトリ '/tmp/test/build/bayesian_belief_networks' に入ります
make[2]: 'CMakeFiles/std_msgs_generate_messages_lisp.dir/build' に対して行うべき事はありません.
make[2]: ディレクトリ '/tmp/test/build/bayesian_belief_networks' から出ます
make[2]: ディレクトリ '/tmp/test/build/bayesian_belief_networks' に入ります
catkin_generated/env_cached.sh /usr/bin/python2 /opt/ros/melodic/share/genmsg/cmake/../../../lib/genmsg/genmsg_check_deps.py bayesian_belief_networks /tmp/test/src/jsk_3rdparty/bayesian_belief_networks/msg/Observation.msg 
make[2]: ディレクトリ '/tmp/test/build/bayesian_belief_networks' に入ります
make[2]: ディレクトリ '/tmp/test/build/bayesian_belief_networks' に入ります
catkin_generated/env_cached.sh /usr/bin/python2 /opt/ros/melodic/share/genmsg/cmake/../../../lib/genmsg/genmsg_check_deps.py bayesian_belief_networks /tmp/test/src/jsk_3rdparty/bayesian_belief_networks/msg/Result.msg 
make[2]: ディレクトリ '/tmp/test/build/bayesian_belief_networks' に入ります
make[2]: 'CMakeFiles/std_msgs_generate_messages_py.dir/build' に対して行うべき事はありません.
make[2]: ディレクトリ '/tmp/test/build/bayesian_belief_networks' から出ます
make[2]: ディレクトリ '/tmp/test/build/bayesian_belief_networks' から出ます
/usr/bin/make -f CMakeFiles/_bayesian_belief_networks_generate_messages_check_deps_Query.dir/build.make CMakeFiles/_bayesian_belief_networks_generate_messages_check_deps_Query.dir/build
make[2]: ディレクトリ '/tmp/test/build/bayesian_belief_networks' に入ります
catkin_generated/env_cached.sh /usr/bin/python2 /opt/ros/melodic/share/genmsg/cmake/../../../lib/genmsg/genmsg_check_deps.py bayesian_belief_networks /tmp/test/src/jsk_3rdparty/bayesian_belief_networks/srv/Query.srv bayesian_belief_networks/Observation:bayesian_belief_networks/Result
[  0%] Built target std_msgs_generate_messages_lisp
[  0%] Built target std_msgs_generate_messages_py
/usr/bin/make -f CMakeFiles/std_msgs_generate_messages_eus.dir/build.make CMakeFiles/std_msgs_generate_messages_eus.dir/depend
[  5%] Generating /tmp/test/src/jsk_3rdparty/bayesian_belief_networks/lib/python2.7/dist-packages/bayesian
/usr/bin/make -f CMakeFiles/std_msgs_generate_messages_nodejs.dir/build.make CMakeFiles/std_msgs_generate_messages_nodejs.dir/depend
make[2]: ディレクトリ '/tmp/test/build/bayesian_belief_networks' に入ります
cd /tmp/test/build/bayesian_belief_networks && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /tmp/test/src/jsk_3rdparty/bayesian_belief_networks /tmp/test/src/jsk_3rdparty/bayesian_belief_networks /tmp/test/build/bayesian_belief_networks /tmp/test/build/bayesian_belief_networks /tmp/test/build/bayesian_belief_networks/CMakeFiles/std_msgs_generate_messages_eus.dir/DependInfo.cmake --color=
cmake -E chdir /tmp/test/build/bayesian_belief_networks make -f /tmp/test/src/jsk_3rdparty/bayesian_belief_networks/Makefile.bayesian MK_DIR=/opt/ros/melodic/share/mk INSTALL_DIR=/tmp/test/src/jsk_3rdparty/bayesian_belief_networks SETUPTOOLS_ARG_EXTRA=--install-layout=deb DIST_DIR=/tmp/test/src/jsk_3rdparty/bayesian_belief_networks/lib/python2.7/dist-packages
make[2]: ディレクトリ '/tmp/test/build/bayesian_belief_networks' に入ります
cd /tmp/test/build/bayesian_belief_networks && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /tmp/test/src/jsk_3rdparty/bayesian_belief_networks /tmp/test/src/jsk_3rdparty/bayesian_belief_networks /tmp/test/build/bayesian_belief_networks /tmp/test/build/bayesian_belief_networks /tmp/test/build/bayesian_belief_networks/CMakeFiles/std_msgs_generate_messages_nodejs.dir/DependInfo.cmake --color=
make[3]: ディレクトリ '/tmp/test/build/bayesian_belief_networks' に入ります
make[3]: 警告: jobserver が利用不可: 今回は -j1 を使います. 親 make ルールに `+' を追加しましょう.
mkdir -p build
make[2]: ディレクトリ '/tmp/test/build/bayesian_belief_networks' から出ます
/usr/bin/make -f CMakeFiles/std_msgs_generate_messages_eus.dir/build.make CMakeFiles/std_msgs_generate_messages_eus.dir/build
if [ ! -f /tmp/test/src/jsk_3rdparty/bayesian_belief_networks/bayesian-belief-networks.zip.md5sum ]; then echo "Error: Couldn't find md5sum file /tmp/test/src/jsk_3rdparty/bayesian_belief_networks/bayesian-belief-networks.zip.md5sum" && false; fi
make[2]: ディレクトリ '/tmp/test/build/bayesian_belief_networks' から出ます
/opt/ros/melodic/share/ros/core/rosbuild/bin/download_checkmd5.py https://github.com/eBay/bayesian-belief-networks/archive/6dd976443610732a5a8ddf08af5fdffbe34dfaec.zip build/bayesian-belief-networks.zip `awk {'print $1'} /tmp/test/src/jsk_3rdparty/bayesian_belief_networks/bayesian-belief-networks.zip.md5sum`
make[2]: ディレクトリ '/tmp/test/build/bayesian_belief_networks' に入ります
make[2]: 'CMakeFiles/std_msgs_generate_messages_eus.dir/build' に対して行うべき事はありません.
make[2]: ディレクトリ '/tmp/test/build/bayesian_belief_networks' から出ます
make[2]: ディレクトリ '/tmp/test/build/bayesian_belief_networks' から出ます
/usr/bin/make -f CMakeFiles/std_msgs_generate_messages_nodejs.dir/build.make CMakeFiles/std_msgs_generate_messages_nodejs.dir/build
make[2]: ディレクトリ '/tmp/test/build/bayesian_belief_networks' から出ます
make[2]: ディレクトリ '/tmp/test/build/bayesian_belief_networks' に入ります
make[2]: 'CMakeFiles/std_msgs_generate_messages_nodejs.dir/build' に対して行うべき事はありません.
make[2]: ディレクトリ '/tmp/test/build/bayesian_belief_networks' から出ます
make[2]: ディレクトリ '/tmp/test/build/bayesian_belief_networks' から出ます
[  5%] Built target _bayesian_belief_networks_generate_messages_check_deps_Result
[  5%] Built target _bayesian_belief_networks_generate_messages_check_deps_Observation
[  5%] Built target std_msgs_generate_messages_eus
/usr/bin/make -f CMakeFiles/std_msgs_generate_messages_cpp.dir/build.make CMakeFiles/std_msgs_generate_messages_cpp.dir/depend
make[2]: ディレクトリ '/tmp/test/build/bayesian_belief_networks' に入ります
cd /tmp/test/build/bayesian_belief_networks && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /tmp/test/src/jsk_3rdparty/bayesian_belief_networks /tmp/test/src/jsk_3rdparty/bayesian_belief_networks /tmp/test/build/bayesian_belief_networks /tmp/test/build/bayesian_belief_networks /tmp/test/build/bayesian_belief_networks/CMakeFiles/std_msgs_generate_messages_cpp.dir/DependInfo.cmake --color=
[  5%] Built target _bayesian_belief_networks_generate_messages_check_deps_Query
/usr/bin/make -f CMakeFiles/bayesian_belief_networks_generate_messages_py.dir/build.make CMakeFiles/bayesian_belief_networks_generate_messages_py.dir/depend
/usr/bin/make -f CMakeFiles/bayesian_belief_networks_generate_messages_lisp.dir/build.make CMakeFiles/bayesian_belief_networks_generate_messages_lisp.dir/depend
/usr/bin/make -f CMakeFiles/bayesian_belief_networks_generate_messages_eus.dir/build.make CMakeFiles/bayesian_belief_networks_generate_messages_eus.dir/depend
make[2]: ディレクトリ '/tmp/test/build/bayesian_belief_networks' に入ります
cd /tmp/test/build/bayesian_belief_networks && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /tmp/test/src/jsk_3rdparty/bayesian_belief_networks /tmp/test/src/jsk_3rdparty/bayesian_belief_networks /tmp/test/build/bayesian_belief_networks /tmp/test/build/bayesian_belief_networks /tmp/test/build/bayesian_belief_networks/CMakeFiles/bayesian_belief_networks_generate_messages_lisp.dir/DependInfo.cmake --color=
make[2]: ディレクトリ '/tmp/test/build/bayesian_belief_networks' に入ります
cd /tmp/test/build/bayesian_belief_networks && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /tmp/test/src/jsk_3rdparty/bayesian_belief_networks /tmp/test/src/jsk_3rdparty/bayesian_belief_networks /tmp/test/build/bayesian_belief_networks /tmp/test/build/bayesian_belief_networks /tmp/test/build/bayesian_belief_networks/CMakeFiles/bayesian_belief_networks_generate_messages_py.dir/DependInfo.cmake --color=
make[2]: ディレクトリ '/tmp/test/build/bayesian_belief_networks' に入ります
cd /tmp/test/build/bayesian_belief_networks && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /tmp/test/src/jsk_3rdparty/bayesian_belief_networks /tmp/test/src/jsk_3rdparty/bayesian_belief_networks /tmp/test/build/bayesian_belief_networks /tmp/test/build/bayesian_belief_networks /tmp/test/build/bayesian_belief_networks/CMakeFiles/bayesian_belief_networks_generate_messages_eus.dir/DependInfo.cmake --color=
[  5%] Built target std_msgs_generate_messages_nodejs
/usr/bin/make -f CMakeFiles/bayesian_belief_networks_generate_messages_nodejs.dir/build.make CMakeFiles/bayesian_belief_networks_generate_messages_nodejs.dir/depend
make[2]: ディレクトリ '/tmp/test/build/bayesian_belief_networks' に入ります
cd /tmp/test/build/bayesian_belief_networks && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /tmp/test/src/jsk_3rdparty/bayesian_belief_networks /tmp/test/src/jsk_3rdparty/bayesian_belief_networks /tmp/test/build/bayesian_belief_networks /tmp/test/build/bayesian_belief_networks /tmp/test/build/bayesian_belief_networks/CMakeFiles/bayesian_belief_networks_generate_messages_nodejs.dir/DependInfo.cmake --color=
make[2]: ディレクトリ '/tmp/test/build/bayesian_belief_networks' から出ます
/usr/bin/make -f CMakeFiles/std_msgs_generate_messages_cpp.dir/build.make CMakeFiles/std_msgs_generate_messages_cpp.dir/build
make[2]: ディレクトリ '/tmp/test/build/bayesian_belief_networks' に入ります
make[2]: 'CMakeFiles/std_msgs_generate_messages_cpp.dir/build' に対して行うべき事はありません.
make[2]: ディレクトリ '/tmp/test/build/bayesian_belief_networks' から出ます
make[2]: ディレクトリ '/tmp/test/build/bayesian_belief_networks' から出ます
/usr/bin/make -f CMakeFiles/bayesian_belief_networks_generate_messages_eus.dir/build.make CMakeFiles/bayesian_belief_networks_generate_messages_eus.dir/build
make[2]: ディレクトリ '/tmp/test/build/bayesian_belief_networks' から出ます
/usr/bin/make -f CMakeFiles/bayesian_belief_networks_generate_messages_lisp.dir/build.make CMakeFiles/bayesian_belief_networks_generate_messages_lisp.dir/build
make[2]: ディレクトリ '/tmp/test/build/bayesian_belief_networks' に入ります
make[2]: 'CMakeFiles/bayesian_belief_networks_generate_messages_eus.dir/build' に対して行うべき事はありません.
make[2]: ディレクトリ '/tmp/test/build/bayesian_belief_networks' から出ます
make[2]: ディレクトリ '/tmp/test/build/bayesian_belief_networks' に入ります
make[2]: 'CMakeFiles/bayesian_belief_networks_generate_messages_lisp.dir/build' に対して行うべき事はありません.
make[2]: ディレクトリ '/tmp/test/build/bayesian_belief_networks' から出ます
make[2]: ディレクトリ '/tmp/test/build/bayesian_belief_networks' から出ます
/usr/bin/make -f CMakeFiles/bayesian_belief_networks_generate_messages_py.dir/build.make CMakeFiles/bayesian_belief_networks_generate_messages_py.dir/build
[rosbuild] Checking md5sum on build/bayesian-belief-networks.zip
[rosbuild] WARNING: md5sum mismatch (90059f6ba38ceb8ef6967c300f4a2da4 != e442af9684af9db7a42d4c22bfd25ca9); re-downloading file build/bayesian-belief-networks.zip
make[2]: ディレクトリ '/tmp/test/build/bayesian_belief_networks' に入ります
make[2]: 'CMakeFiles/bayesian_belief_networks_generate_messages_py.dir/build' に対して行うべき事はありません.
make[2]: ディレクトリ '/tmp/test/build/bayesian_belief_networks' から出ます
[  5%] Built target std_msgs_generate_messages_cpp
/usr/bin/make -f CMakeFiles/bayesian_belief_networks_generate_messages_cpp.dir/build.make CMakeFiles/bayesian_belief_networks_generate_messages_cpp.dir/depend
make[2]: ディレクトリ '/tmp/test/build/bayesian_belief_networks' から出ます
/usr/bin/make -f CMakeFiles/bayesian_belief_networks_generate_messages_nodejs.dir/build.make CMakeFiles/bayesian_belief_networks_generate_messages_nodejs.dir/build
make[2]: ディレクトリ '/tmp/test/build/bayesian_belief_networks' に入ります
cd /tmp/test/build/bayesian_belief_networks && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /tmp/test/src/jsk_3rdparty/bayesian_belief_networks /tmp/test/src/jsk_3rdparty/bayesian_belief_networks /tmp/test/build/bayesian_belief_networks /tmp/test/build/bayesian_belief_networks /tmp/test/build/bayesian_belief_networks/CMakeFiles/bayesian_belief_networks_generate_messages_cpp.dir/DependInfo.cmake --color=
make[2]: ディレクトリ '/tmp/test/build/bayesian_belief_networks' に入ります
make[2]: 'CMakeFiles/bayesian_belief_networks_generate_messages_nodejs.dir/build' に対して行うべき事はありません.
make[2]: ディレクトリ '/tmp/test/build/bayesian_belief_networks' から出ます
[ 31%] Built target bayesian_belief_networks_generate_messages_py
[ 68%] Built target bayesian_belief_networks_generate_messages_lisp
[ 68%] Built target bayesian_belief_networks_generate_messages_eus
[ 84%] Built target bayesian_belief_networks_generate_messages_nodejs
make[2]: ディレクトリ '/tmp/test/build/bayesian_belief_networks' から出ます
/usr/bin/make -f CMakeFiles/bayesian_belief_networks_generate_messages_cpp.dir/build.make CMakeFiles/bayesian_belief_networks_generate_messages_cpp.dir/build
make[2]: ディレクトリ '/tmp/test/build/bayesian_belief_networks' に入ります
make[2]: 'CMakeFiles/bayesian_belief_networks_generate_messages_cpp.dir/build' に対して行うべき事はありません.
make[2]: ディレクトリ '/tmp/test/build/bayesian_belief_networks' から出ます
[100%] Built target bayesian_belief_networks_generate_messages_cpp
/usr/bin/make -f CMakeFiles/bayesian_belief_networks_generate_messages.dir/build.make CMakeFiles/bayesian_belief_networks_generate_messages.dir/depend
make[2]: ディレクトリ '/tmp/test/build/bayesian_belief_networks' に入ります
cd /tmp/test/build/bayesian_belief_networks && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /tmp/test/src/jsk_3rdparty/bayesian_belief_networks /tmp/test/src/jsk_3rdparty/bayesian_belief_networks /tmp/test/build/bayesian_belief_networks /tmp/test/build/bayesian_belief_networks /tmp/test/build/bayesian_belief_networks/CMakeFiles/bayesian_belief_networks_generate_messages.dir/DependInfo.cmake --color=
Dependee "/tmp/test/build/bayesian_belief_networks/CMakeFiles/bayesian_belief_networks_generate_messages.dir/DependInfo.cmake" is newer than depender "/tmp/test/build/bayesian_belief_networks/CMakeFiles/bayesian_belief_networks_generate_messages.dir/depend.internal".
Dependee "/tmp/test/build/bayesian_belief_networks/CMakeFiles/CMakeDirectoryInformation.cmake" is newer than depender "/tmp/test/build/bayesian_belief_networks/CMakeFiles/bayesian_belief_networks_generate_messages.dir/depend.internal".
Scanning dependencies of target bayesian_belief_networks_generate_messages
make[2]: ディレクトリ '/tmp/test/build/bayesian_belief_networks' から出ます
/usr/bin/make -f CMakeFiles/bayesian_belief_networks_generate_messages.dir/build.make CMakeFiles/bayesian_belief_networks_generate_messages.dir/build
make[2]: ディレクトリ '/tmp/test/build/bayesian_belief_networks' に入ります
make[2]: 'CMakeFiles/bayesian_belief_networks_generate_messages.dir/build' に対して行うべき事はありません.
make[2]: ディレクトリ '/tmp/test/build/bayesian_belief_networks' から出ます
[100%] Built target bayesian_belief_networks_generate_messages
[rosbuild] ERROR: md5sum mismatch (90059f6ba38ceb8ef6967c300f4a2da4 != e442af9684af9db7a42d4c22bfd25ca9) on build/bayesian-belief-networks.zip; aborting
/opt/ros/melodic/share/mk/download_unpack_build.mk:37: recipe for target 'build/bayesian-belief-networks-6dd976443610732a5a8ddf08af5fdffbe34dfaec/unpacked' failed
make[3]: ディレクトリ '/tmp/test/build/bayesian_belief_networks' から出ます
make[3]: *** [build/bayesian-belief-networks-6dd976443610732a5a8ddf08af5fdffbe34dfaec/unpacked] Error 1
CMakeFiles/python_baysian_belief_networks_download.dir/build.make:60: recipe for target '/tmp/test/src/jsk_3rdparty/bayesian_belief_networks/lib/python2.7/dist-packages/bayesian' failed
make[2]: ディレクトリ '/tmp/test/build/bayesian_belief_networks' から出ます
make[2]: *** [/tmp/test/src/jsk_3rdparty/bayesian_belief_networks/lib/python2.7/dist-packages/bayesian] Error 2
CMakeFiles/Makefile2:393: recipe for target 'CMakeFiles/python_baysian_belief_networks_download.dir/all' failed
make[1]: ディレクトリ '/tmp/test/build/bayesian_belief_networks' から出ます
make[1]: *** [CMakeFiles/python_baysian_belief_networks_download.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
cd /tmp/test/build/bayesian_belief_networks; catkin build --get-env bayesian_belief_networks | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -
..................................................................................................................................................................................................................
Failed     << bayesian_belief_networks:make           [ Exited with code 2 ]                                                                                                                                      
Failed    <<< bayesian_belief_networks                [ 0.7 seconds ]                                                                                                                                             
[build] Summary: 0 of 1 packages succeeded.                                                                                                                                                                       
[build]   Ignored:   31 packages were skipped or are blacklisted.                                                                                                                                                 
[build]   Warnings:  None.                                                                                                                                                                                        
[build]   Abandoned: None.                                                                                                                                                                                        
[build]   Failed:    1 packages failed.                                                                                                                                                                           
[build] Runtime: 0.8 seconds total.  
```

**Comment by mqcmd196** [comment]
This comment is just note for me ...
I've tested how `zip` `md5sum` command works in my machine
```bash
zip -r test_dir.zip jsk_3rdparty/
md5sum test_dir.zip
```
returns
```
30bee6d0faaf116237c5f89fd7d9fbec  test_dir.zip
```
. And remove this zip file and execute `zip` again
```bash
rm test_dir.zip 
zip -r test_dir.zip jsk_3rdparty/
md5sum test_dir.zip
```
returns
```
e78a5c53ad670650f57d4e824bb26eaa  test_dir.zip
```
. MD5 varies when `zip` command executed even the directories are completely same thing.

**Comment by mqcmd196** [comment]
FYI: https://twitter.com/shs96c/status/1488480089700503558 ...?

**Comment by 708yamaguchi** [comment]
Nice catch!

I see that some of the github archive files have had their md5sum changed, although the contents have not been changed.

I think it is better to wait for additional information, such as the official announcement on github.

**Comment by 708yamaguchi** [comment]
As a temporary solution, I think https://github.com/jsk-ros-pkg/jsk_3rdparty/pull/330 is effective.

**Comment by 708yamaguchi** [comment]
It seems that the problem is fixed.

In my local environment, catkin build finished successfully.

**Comment by mqcmd196** [comment]
> It seems that the problem is fixed.
> 
> In my local environment, catkin build finished successfully.

Yes, it seems so, I also did it successfully. https://github.com/emscripten-core/emscripten/issues/16164 says same thing. I'll close this issue, but we have to remember this trouble and reopen if it occurs again.

**Pull request closed without merging**
