### PR TITLE
[rostwitter] add tweet_image_server.py

### PR DESCRIPTION
**Pull request by knorth55**
this is refined node of https://github.com/jsk-ros-pkg/jsk_robot/pull/1298

I add `tweet_image_server.py` node.
We can tweet + image + robot-speaking easily with `rosservice call /tweet_image_server/tweet`.
Currently, only euslisp user can tweet+image+robot-speaking easily, but with this PR, all ROS users can tweet easily.

I tested with PR1040
https://twitter.com/pr2jsk/status/1352610634920120321

### CODE REVIEW

**Comment by k-okada** [comment]
why you choose service, the control program need to wait for twitter post?

**Comment by knorth55** [comment]
@k-okada I'm using this program for app_manager plugin.
In the plugin, robot tweet before or after the task, and the plugin wants if tweet is succeeded or not.
However, topic is also reasonable, so I can also add topic to tweet.

**Comment by k-okada** [comment]
in that case you can use Action
--
◉ Kei Okada



2021年5月9日(日) 10:41 Shingo Kitagawa ***@***.***>:

**Comment by knorth55** [comment]
OK, I will change to use `action`.
I prefer `action` but this node is quick, so I think we can use `service`.
http://wiki.ros.org/ROS/Patterns/Communication

BTW, `action` is implemented in `topic` in ROS1, but it is implemented as `service` in ROS2.
I didn't know that...
https://docs.ros.org/en/foxy/Tutorials/Understanding-ROS2-Actions.html#background

**Comment by k-okada** [comment]
most robotics systems designed as data-flow systems ,not only ROS and RTM,
but also hrpsys/nervous, even subsumption architecture ..... But, once they
provide such systems, users request service call style communication, then
they have to implement a service call interface to their original design.

see historical commit when service is introduced
https://github.com/OpenRTM/OpenRTM-aist/commit/951aed4525389ac06ebe8480e80eb1e444440fd2#diff-7e5c5525d260360b2a74418cfdc51605cfa0cb4d954110646cd2cc092e44aafc
https://sourceforge.net/p/ros/code/1230/

I believe "action" is a great invention which requests request-response
style communication over data-flow systems, so you can use them for both
style (data-flow and request-response communication) and once action is
introduced, we have no reason to use service call in my opinion.

--
◉ Kei Okada



2021年5月10日(月) 19:48 Shingo Kitagawa ***@***.***>:

**Comment by knorth55** [comment]
I update to use `action` for `rostwitter`.

**Pull request merged**
