### PR TITLE
Using RespeakerInterface instead of init_respeaker

### PR DESCRIPTION
**Pull request by dgorissen**
- import statement refers to non-existing init_respeaker function, replaced with RespeakerInterface
- cfg directory does not exist, changed to config, which does exist by default

Tested and works for me on ROS1 with 

rosrun respeaker_ros respeaker_gencfg.py

After which this then runs successfully

rosrun respeaker_ros respeaker_node.py

### CODE REVIEW

**Comment by dgorissen** [comment]
Actually, the directory change from cfg -> config is probably not appropriate, but I did get an error that "cfg" did not exist at some point.

**Comment by 708yamaguchi** [comment]
Hi dgorissen, thank you for your contribution.

> but I did get an error that "cfg" did not exist at some point.

Do you mean `outpath` is not correctly set?
https://github.com/jsk-ros-pkg/jsk_3rdparty/blob/6b964fe1c5ad09fbc433819a49e1e110ab55ad6d/respeaker_ros/scripts/respeaker_gencfg.py#L73-L75

Or do you mean that `cfg` directory is not found under `/opt/ros/$ROS_DISTRO/share/respeaker_ros`?
```
$ ls /opt/ros/$ROS_DISTRO/share/respeaker_ros
cmake  config  launch  package.xml  scripts
```

If the former is the cause, you need to edit the outpath.
It may be that relative path using `..` is not a good.

If the latter is the cause, try the source version of respeaker_ros.

**Comment by dgorissen** [comment]
Thanks @708yamaguchi
Regarding the `cfg` directory, I am running the source version and at some point `cfg` did not exist in `<catkin workspace>/src/respeaker_ros`. The `config` directory did exist however so I thought that at some point the directory name just changed, so hence I changed it.  

However, reviewing everything I think it may have been an error on my part so I will revert that change. The other change should remain to my knowledge.

**Review by 708yamaguchi — APPROVED** [review]

**Comment by dgorissen** [comment]
Looking through the failed checks these look unrelated to the change, rather errors seem to be about missing or broken dependencies. For example:

```
ERROR: rosdep-modules 0.21.0 has requirement rospkg>=1.3.0, but you'll have rospkg 1.2.6 which is incompatible.
  ERROR: rosdep 0.21.0 has requirement rospkg>=1.3.0, but you'll have rospkg 1.2.6 which is incompatible.
```

**Pull request merged**
