### PR TITLE
[libcmt] Depends on opencv2

### PR DESCRIPTION
**Pull request by garaemon**

### CODE REVIEW

**Comment by garaemon** [comment]
2.0.8 has been released

**Comment by k-okada** [comment]
This should be `libopencv-dev` ?
```
k-okada@kokada-t440s:~$ ROS_DISTRO=groovy rosdep resolve opencv2

ERROR: No definition of [opencv2] for OS version [trusty]

No definition of [opencv2] for OS version [trusty]
	rosdep key : opencv2
	OS name    : ubuntu
	OS version : trusty
	Data: _is_ros: true
osx:
  homebrew:
    packages:
    - ros/groovy/opencv2
ubuntu:
  oneiric:
    apt:
      packages:
      - ros-groovy-opencv2
  precise:
    apt:
      packages:
      - ros-groovy-opencv2
  quantal:
    apt:
      packages:
      - ros-groovy-opencv2


k-okada@kokada-t440s:~$ ROS_DISTRO=hydro rosdep resolve opencv2

ERROR: No definition of [opencv2] for OS version [trusty]

No definition of [opencv2] for OS version [trusty]
	rosdep key : opencv2
	OS name    : ubuntu
	OS version : trusty
	Data: _is_ros: true
fedora:
  heisenbug:
    yum:
      packages:
      - ros-hydro-opencv2
osx:
  homebrew:
    packages:
    - ros/hydro/opencv2
ubuntu:
  precise:
    apt:
      packages:
      - ros-hydro-opencv2
  quantal:
    apt:
      packages:
      - ros-hydro-opencv2
  raring:
    apt:
      packages:
      - ros-hydro-opencv2


k-okada@kokada-t440s:~$ ROS_DISTRO=hydro rosdep resolve libopencv-dev
#apt
libopencv-dev
k-okada@kokada-t440s:~$ ROS_DISTRO=indigo rosdep resolve libopencv-dev
#apt
libopencv-dev
k-okada@kokada-t440s:~$ ROS_DISTRO=jade rosdep resolve libopencv-dev
#apt
libopencv-dev
```

**Comment by k-okada** [comment]
created PR for #23

**Comment by garaemon** [comment]
Is it true?
on 12.04, libopencv-dev is not available?
```
$ ROS_DISTRO=hydro rosdep resolve libopencv-dev

ERROR: No definition of [libopencv-dev] for OS version [precise]

No definition of [libopencv-dev] for OS version [precise]
        rosdep key : libopencv-dev
        OS name    : ubuntu
        OS version : precise
        Data: arch:
- opencv
debian:
- libopencv-dev
fedora:
- opencv-devel
gentoo:
- media-libs/opencv
macports:
- opencv
ubuntu:
  saucy:
  - libopencv-dev
  trusty:
  - libopencv-dev
  utopic:
  - libopencv-dev
  vivid:
  - libopencv-dev
```

**Comment by garaemon** [comment]
```
$ ROS_DISTRO=hydro rosdep resolve opencv2
#apt
ros-hydro-opencv2
```

**Comment by garaemon** [comment]
```
libopencv-dev:
  arch: [opencv]
  debian: [libopencv-dev]
  fedora: [opencv-devel]
  gentoo: [media-libs/opencv]
  macports: [opencv]
  ubuntu:
    saucy: [libopencv-dev]
    trusty: [libopencv-dev]
    utopic: [libopencv-dev]
    vivid: [libopencv-dev]
```
https://github.com/ros/rosdistro/blob/master/rosdep/base.yaml#L1727

**Pull request merged**
