### PR TITLE
[3rdparty] add libcmt

### PR DESCRIPTION
**Pull request by aginika**

### CODE REVIEW

**Comment by garaemon** [comment]
Please install libraries and headers for `catkin install`.

**Comment by k-okada** [comment]
if the library is stable enough, I think best way it to release them directory, as we do in https://github.com/tork-a/jskeus-release/tree/master

**Comment by k-okada** [comment]
to do so, first please cleanup package.xml, fix LISENCE, update maintainer's e-mail also update run/build depends...

**Comment by garaemon** [comment]
> I think the best way is to release them directory

Are there any pros to release them directory?

cons are:
* difficult to compile from source: need to download package.xml from release repository
* need to maintain another repository

**Comment by k-okada** [comment]
pros:
   do not have to maintain package that download during compile process,
that super hard to keep them working (
http://jenkins.ros.org/job/ros-jade-ff_binarydeb_vivid_amd64/16/console,
https://github.com/k-okada/ar_tools/commits/2e20b3418b2c46bb83e6fca12cc804d1cf68854d/artoolkit/CMakeLists.txt
)

cons:
   if you wan to contribute to the library, it hard download source code

So question is whether you want to contribute to this library or not.

--
◉ Kei Okada

**Comment by garaemon** [comment]
> do not have to maintain package that download during compile process

It's a great advantage.



> So question is whether you want to contribute to this library or not.

I am afraid that we need to modify upstream a little bit to use the library about API and so on.

**Comment by k-okada** [comment]
how about sending several PR for  cmake and API to upstream and if they
accept our PR quickly, then we do not have to keep source code so we can
directly release this library, if not we'll keep this package within
3rdparty.

--
◉ Kei Okada

**Comment by garaemon** [comment]
> how about sending several PR for  cmake and API to upstream and if they
> accept our PR quickly, then we do not have to keep source code so we can
> directly release this library, if not we'll keep this package within
> 3rdparty.

Sounds good.

**Comment by aginika** [comment]
Sorry, 
So What should I do for upstream?

**Comment by garaemon** [comment]
> Sorry, 
> So What should I do for upstream?

send PR anyway and we will check activity of upstream repository

**Comment by k-okada** [comment]
https://github.com/aginika/libCMT/commit/5e0534f082edb7170e47efeb49ae5c7df7ca0ce3
and

> I am afraid that we need to modify upstream a little bit to use the
library about API and so on.

.

--
◉ Kei Okada

**Comment by aginika** [comment]
I sent PR.

**Comment by aginika** [comment]
The first time compile will not fail, but the compile after that will begin to fail with below error...
I couldn't find out this error cause, so could anyone tell me how I can fix it?
```
[100%] Built target main
Install the project...
-- Install configuration: ""
-- Up-to-date: /home/aginika/ros/hydro/devel/lib/libcmt.so
CMake Error at cmake_install.cmake:42 (FILE):
  file INSTALL cannot set permissions on
  "/home/aginika/ros/hydro/devel/lib/libcmt.so"


```

**Comment by k-okada** [comment]
could not reproduce this

```
k-okada@kokada-t440s:/tmp/hoge$ catkin clean -a
[clean] Removing buildspace: /tmp/hoge/build
[clean] Removing develspace: /tmp/hoge/devel
[clean] Removing installspace: /tmp/hoge/install
k-okada@kokada-t440s:/tmp/hoge$ catkin b -v -i libcmt
==> Expanding alias 'b' from 'catkin b -v -i libcmt' to 'catkin build -v -i libcmt'
Creating build space directory, '/tmp/hoge/build' 
----------------------------------------------
Profile:                     default
Extending:             [env] /opt/ros/indigo
Workspace:                   /tmp/hoge
Source Space:       [exists] /tmp/hoge/src
Build Space:        [exists] /tmp/hoge/build
Devel Space:       [missing] /tmp/hoge/devel
Install Space:     [missing] /tmp/hoge/install
DESTDIR:                     None
----------------------------------------------
Isolate Develspaces:         False
Install Packages:            False
Isolate Installs:            False
----------------------------------------------
Additional CMake Args:       None
Additional Make Args:        None
Additional catkin Make Args: None
Internal Make Job Server:    True
----------------------------------------------
Whitelisted Packages:        None
Blacklisted Packages:        None
----------------------------------------------
Workspace configuration appears valid.
---------------------------------------------- 
Found '20' packages in 0.0 seconds. 
Starting ==> libcmt                                                                                                         
[libcmt] ==> '/tmp/hoge/build/libcmt/build_env.sh /usr/bin/cmake /tmp/hoge/src/jsk_3rdparty/3rdparty/libcmt -DCATKIN_DEVEL_PREFIX=/tmp/hoge/devel -DCMAKE_INSTALL_PREFIX=/tmp/hoge/install' in '/tmp/hoge/build/libcmt' 
[libcmt] -- The C compiler identification is GNU 4.8.4                                                                      
[libcmt] -- The CXX compiler identification is GNU 4.8.4                                                                    
[libcmt] -- Check for working C compiler: /usr/bin/cc                                                                       
[libcmt] -- Check for working C compiler: /usr/bin/cc -- works                                                              
[libcmt] -- Detecting C compiler ABI info                                                                                   
[libcmt] -- Detecting C compiler ABI info - done                                                                            
[libcmt] -- Check for working CXX compiler: /usr/bin/c++                                                                    
[libcmt] -- Check for working CXX compiler: /usr/bin/c++ -- works                                                           
[libcmt] -- Detecting CXX compiler ABI info                                                                                 
[libcmt] -- Detecting CXX compiler ABI info - done                                                                          
[libcmt] -- Using CATKIN_DEVEL_PREFIX: /tmp/hoge/devel                                                                      
[libcmt] -- Using CMAKE_PREFIX_PATH: /opt/ros/indigo                                                                        
[libcmt] -- This workspace overlays: /opt/ros/indigo                                                                        
[libcmt] -- Found PythonInterp: /usr/bin/python (found version "2.7.6")                                                     
[libcmt] -- Using PYTHON_EXECUTABLE: /usr/bin/python                                                                        
[libcmt] -- Using Debian Python package layout                                                                              
[libcmt] -- Using empy: /usr/bin/empy                                                                                       
[libcmt] -- Using CATKIN_ENABLE_TESTING: ON                                                                                 
[libcmt] -- Call enable_testing()                                                                                           
[libcmt] -- Using CATKIN_TEST_RESULTS_DIR: /tmp/hoge/build/libcmt/test_results                                              
[libcmt] -- Looking for include file pthread.h                                                                              
[libcmt] -- Looking for include file pthread.h - found                                                                      
[libcmt] -- Looking for pthread_create                                                                                      
[libcmt] -- Looking for pthread_create - not found                                                                          
[libcmt] -- Looking for pthread_create in pthreads                                                                          
[libcmt] -- Looking for pthread_create in pthreads - not found                                                              
[libcmt] -- Looking for pthread_create in pthread                                                                           
[libcmt] -- Looking for pthread_create in pthread - found                                                                   
[libcmt] -- Found Threads: TRUE                                                                                             
[libcmt] -- Found gtest sources under '/usr/src/gtest': gtests will be built                                                
[libcmt] -- Using Python nosetests: /usr/bin/nosetests-2.7                                                                  
[libcmt] -- catkin 0.6.14                                                                                                   
[libcmt] -- Found Git: /usr/bin/git (found version "1.9.1")                                                                 
[libcmt] -- Configuring done                                                                                                
[libcmt] -- Generating done                                                                                                 
[libcmt] -- Build files have been written to: /tmp/hoge/build/libcmt                                                        
[libcmt] <== '/tmp/hoge/build/libcmt/build_env.sh /usr/bin/cmake /tmp/hoge/src/jsk_3rdparty/3rdparty/libcmt -DCATKIN_DEVEL_PREFIX=/tmp/hoge/devel -DCMAKE_INSTALL_PREFIX=/tmp/hoge/install' finished with return code '0' 
[libcmt] ==> '/tmp/hoge/build/libcmt/build_env.sh /usr/bin/make --jobserver-fds=3,4 -j' in '/tmp/hoge/build/libcmt'         
[libcmt] Scanning dependencies of target libcmt                                                                             
[libcmt] [ 12%] Creating directories for 'libcmt'                                                                           
[libcmt] [ 25%] Performing download step (git clone) for 'libcmt'                                                           
[libcmt] Cloning into 'libcmt'...                                                                                           
[libcmt] remote: Counting objects: 86, done.                                                                                
[libcmt] remote: Compressing objects:  11% (1/9)                                                                            
[libcmt] remote: Compressing objects:  22% (2/9)                                                                            
[libcmt] remote: Compressing objects:  33% (3/9)                                                                            
[libcmt] remote: Compressing objects:  44% (4/9)                                                                            
[libcmt] remote: Compressing objects:  55% (5/9)                                                                            
[libcmt] remote: Compressing objects:  66% (6/9)                                                                            
[libcmt] remote: Compressing objects:  77% (7/9)                                                                            
[libcmt] remote: Compressing objects:  88% (8/9)                                                                            
[libcmt] remote: Compressing objects: 100% (9/9)                                                                            
[libcmt] remote: Compressing objects: 100% (9/9), done.                                                                     
[libcmt] Unpacking objects:   1% (1/86)                                                                                     
[libcmt] Unpacking objects:   2% (2/86)                                                                                     
[libcmt] Unpacking objects:   3% (3/86)                                                                                     
[libcmt] Unpacking objects:   4% (4/86)                                                                                     
[libcmt] Unpacking objects:   5% (5/86)                                                                                     
[libcmt] Unpacking objects:   6% (6/86)                                                                                     
[libcmt] Unpacking objects:   8% (7/86)                                                                                     
[libcmt] Unpacking objects:   9% (8/86)                                                                                     
[libcmt] Unpacking objects:  10% (9/86)                                                                                     
[libcmt] Unpacking objects:  11% (10/86)                                                                                    
[libcmt] Unpacking objects:  12% (11/86)                                                                                    
[libcmt] Unpacking objects:  13% (12/86)                                                                                    
[libcmt] Unpacking objects:  15% (13/86)                                                                                    
[libcmt] Unpacking objects:  16% (14/86)                                                                                    
[libcmt] Unpacking objects:  17% (15/86)                                                                                    
[libcmt] Unpacking objects:  18% (16/86)                                                                                    
[libcmt] Unpacking objects:  19% (17/86)                                                                                    
[libcmt] Unpacking objects:  20% (18/86)                                                                                    
[libcmt] Unpacking objects:  22% (19/86)                                                                                    
[libcmt] Unpacking objects:  23% (20/86)                                                                                    
[libcmt] Unpacking objects:  24% (21/86)                                                                                    
[libcmt] Unpacking objects:  25% (22/86)                                                                                    
[libcmt] Unpacking objects:  26% (23/86)                                                                                    
[libcmt] Unpacking objects:  27% (24/86)                                                                                    
[libcmt] Unpacking objects:  29% (25/86)                                                                                    
[libcmt] Unpacking objects:  30% (26/86)                                                                                    
[libcmt] Unpacking objects:  31% (27/86)                                                                                    
[libcmt] Unpacking objects:  32% (28/86)                                                                                    
[libcmt] Unpacking objects:  33% (29/86)                                                                                    
[libcmt] Unpacking objects:  34% (30/86)                                                                                    
[libcmt] Unpacking objects:  36% (31/86)                                                                                    
[libcmt] Unpacking objects:  37% (32/86)                                                                                    
[libcmt] Unpacking objects:  38% (33/86)                                                                                    
[libcmt] Unpacking objects:  39% (34/86)                                                                                    
[libcmt] Unpacking objects:  40% (35/86)                                                                                    
[libcmt] Unpacking objects:  41% (36/86)                                                                                    
[libcmt] Unpacking objects:  43% (37/86)                                                                                    
[libcmt] Unpacking objects:  44% (38/86)                                                                                    
[libcmt] Unpacking objects:  45% (39/86)                                                                                    
[libcmt] Unpacking objects:  46% (40/86)                                                                                    
[libcmt] Unpacking objects:  47% (41/86)                                                                                    
[libcmt] Unpacking objects:  48% (42/86)                                                                                    
[libcmt] Unpacking objects:  50% (43/86)                                                                                    
[libcmt] Unpacking objects:  51% (44/86)                                                                                    
[libcmt] Unpacking objects:  52% (45/86)                                                                                    
[libcmt] Unpacking objects:  53% (46/86)                                                                                    
[libcmt] Unpacking objects:  54% (47/86)                                                                                    
[libcmt] Unpacking objects:  55% (48/86)                                                                                    
[libcmt] Unpacking objects:  56% (49/86)                                                                                    
[libcmt] Unpacking objects:  58% (50/86)                                                                                    
[libcmt] Unpacking objects:  59% (51/86)                                                                                    
[libcmt] remote: Total 86 (delta 5), reused 0 (delta 0), pack-reused 77                                                     
[libcmt] Unpacking objects:  60% (52/86)                                                                                    
[libcmt] Unpacking objects:  61% (53/86)                                                                                    
[libcmt] Unpacking objects:  62% (54/86)                                                                                    
[libcmt] Unpacking objects:  63% (55/86)                                                                                    
[libcmt] Unpacking objects:  65% (56/86)                                                                                    
[libcmt] Unpacking objects:  66% (57/86)                                                                                    
[libcmt] Unpacking objects:  67% (58/86)                                                                                    
[libcmt] Unpacking objects:  68% (59/86)                                                                                    
[libcmt] Unpacking objects:  69% (60/86)                                                                                    
[libcmt] Unpacking objects:  70% (61/86)                                                                                    
[libcmt] Unpacking objects:  72% (62/86)                                                                                    
[libcmt] Unpacking objects:  73% (63/86)                                                                                    
[libcmt] Unpacking objects:  74% (64/86)                                                                                    
[libcmt] Unpacking objects:  75% (65/86)                                                                                    
[libcmt] Unpacking objects:  76% (66/86)                                                                                    
[libcmt] Unpacking objects:  77% (67/86)                                                                                    
[libcmt] Unpacking objects:  79% (68/86)                                                                                    
[libcmt] Unpacking objects:  80% (69/86)                                                                                    
[libcmt] Unpacking objects:  81% (70/86)                                                                                    
[libcmt] Unpacking objects:  82% (71/86)                                                                                    
[libcmt] Unpacking objects:  83% (72/86)                                                                                    
[libcmt] Unpacking objects:  84% (73/86)                                                                                    
[libcmt] Unpacking objects:  86% (74/86)                                                                                    
[libcmt] Unpacking objects:  87% (75/86)                                                                                    
[libcmt] Unpacking objects:  88% (76/86)                                                                                    
[libcmt] Unpacking objects:  89% (77/86)                                                                                    
[libcmt] Unpacking objects:  90% (78/86)                                                                                    
[libcmt] Unpacking objects:  91% (79/86)                                                                                    
[libcmt] Unpacking objects:  93% (80/86)                                                                                    
[libcmt] Unpacking objects:  94% (81/86)                                                                                    
[libcmt] Unpacking objects:  95% (82/86)                                                                                    
[libcmt] Unpacking objects:  96% (83/86)                                                                                    
[libcmt] Unpacking objects:  97% (84/86)                                                                                    
[libcmt] Unpacking objects:  98% (85/86)                                                                                    
[libcmt] Unpacking objects: 100% (86/86)                                                                                    
[libcmt] Unpacking objects: 100% (86/86), done.                                                                             
[libcmt] Checking connectivity... done.                                                                                     
[libcmt] Switched to a new branch 'add-make-install'                                                                        
[libcmt] Branch add-make-install set up to track remote branch add-make-install from origin.                                
[libcmt] [ 37%] [ 50%] Performing update step for 'libcmt'                                                                  
[libcmt] No patch step for 'libcmt'                                                                                         
[libcmt] Already on 'add-make-install'                                                                                      
[libcmt] Your branch is up-to-date with 'origin/add-make-install'.                                                          
[libcmt] [ 62%] Performing configure step for 'libcmt'                                                                      
[libcmt] -- The C compiler identification is GNU 4.8.4                                                                      
[libcmt] -- The CXX compiler identification is GNU 4.8.4                                                                    
[libcmt] -- Check for working C compiler: /usr/bin/cc                                                                       
[libcmt] -- Check for working C compiler: /usr/bin/cc -- works                                                              
[libcmt] -- Detecting C compiler ABI info                                                                                   
[libcmt] -- Detecting C compiler ABI info - done                                                                            
[libcmt] -- Check for working CXX compiler: /usr/bin/c++                                                                    
[libcmt] -- Check for working CXX compiler: /usr/bin/c++ -- works                                                           
[libcmt] -- Detecting CXX compiler ABI info                                                                                 
[libcmt] -- Detecting CXX compiler ABI info - done                                                                          
[libcmt] -- Configuring done                                                                                                
[libcmt] -- Generating done                                                                                                 
[libcmt] -- Build files have been written to: /tmp/hoge/build/libcmt/libcmt-prefix/src/libcmt-build                         
[libcmt] [ 75%] Performing build step for 'libcmt'                                                                          
[libcmt] Scanning dependencies of target cmt                                                                                
[libcmt] [ 50%] Building CXX object CMakeFiles/cmt.dir/CMT.cpp.o                                                            
[libcmt] Linking CXX shared library lib/libcmt.so                                                                           
[libcmt] [ 50%] Built target cmt                                                                                            
[libcmt] Scanning dependencies of target main                                                                               
[libcmt] [100%] Building CXX object CMakeFiles/main.dir/main.cpp.o                                                          
[libcmt] /tmp/hoge/build/libcmt/libcmt-prefix/src/libcmt/main.cpp: In function int main(int, char**):                       
[libcmt] /tmp/hoge/build/libcmt/libcmt-prefix/src/libcmt/main.cpp:24:18: warning: deprecated conversion from string constant to char* [-Wwrite-strings] 
[libcmt]      char *path = "sequences/cokecan/img";                                                                         
[libcmt]                   ^                                                                                                
[libcmt] /tmp/hoge/build/libcmt/libcmt-prefix/src/libcmt/main.cpp:25:17: warning: deprecated conversion from string constant to char* [-Wwrite-strings] 
[libcmt]      char *ext = "png";                                                                                            
[libcmt]                  ^                                                                                                 
[libcmt] Linking CXX executable bin/main                                                                                    
[libcmt] [100%] Built target main                                                                                           
[libcmt] [ 87%] Performing install step for 'libcmt'                                                                        
[libcmt] [ 50%] Built target cmt                                                                                            
[libcmt] [100%] Built target main                                                                                           
[libcmt] Install the project...                                                                                             
[libcmt] -- Install configuration: ""                                                                                       
[libcmt] -- Installing: /tmp/hoge/devel/lib/libcmt.so                                                                       
[libcmt] -- Installing: /tmp/hoge/devel/include/libcmt/CMT.h                                                                
[libcmt] [100%] Completed 'libcmt'                                                                                          
[libcmt] [100%] Built target libcmt                                                                                         
[libcmt] <== '/tmp/hoge/build/libcmt/build_env.sh /usr/bin/make --jobserver-fds=3,4 -j' finished with return code '0'       
Finished <== libcmt [ 7.0 seconds ]                                                                                         
[build] Finished.                                                                                                           
[build] Runtime: 7.1 seconds 
k-okada@kokada-t440s:/tmp/hoge$ catkin b -v -i libcmt
==> Expanding alias 'b' from 'catkin b -v -i libcmt' to 'catkin build -v -i libcmt'
----------------------------------------------
Profile:                     default
Extending:          [cached] /opt/ros/indigo
Workspace:                   /tmp/hoge
Source Space:       [exists] /tmp/hoge/src
Build Space:        [exists] /tmp/hoge/build
Devel Space:        [exists] /tmp/hoge/devel
Install Space:     [missing] /tmp/hoge/install
DESTDIR:                     None
----------------------------------------------
Isolate Develspaces:         False
Install Packages:            False
Isolate Installs:            False
----------------------------------------------
Additional CMake Args:       None
Additional Make Args:        None
Additional catkin Make Args: None
Internal Make Job Server:    True
----------------------------------------------
Whitelisted Packages:        None
Blacklisted Packages:        None
----------------------------------------------
Workspace configuration appears valid.
---------------------------------------------- 
Found '20' packages in 0.0 seconds. 
Starting ==> libcmt                                                                                                         
[libcmt] ==> '/tmp/hoge/build/libcmt/build_env.sh /usr/bin/make cmake_check_build_system' in '/tmp/hoge/build/libcmt'       
[libcmt] <== '/tmp/hoge/build/libcmt/build_env.sh /usr/bin/make cmake_check_build_system' finished with return code '0'     
[libcmt] ==> '/tmp/hoge/build/libcmt/build_env.sh /usr/bin/make --jobserver-fds=3,5 -j' in '/tmp/hoge/build/libcmt'         
[libcmt] [ 12%] Performing update step for 'libcmt'                                                                         
[libcmt] Already on 'add-make-install'                                                                                      
[libcmt] Your branch is up-to-date with 'origin/add-make-install'.                                                          
[libcmt] [ 25%] Performing configure step for 'libcmt'                                                                      
[libcmt] -- Configuring done                                                                                                
[libcmt] -- Generating done                                                                                                 
[libcmt] -- Build files have been written to: /tmp/hoge/build/libcmt/libcmt-prefix/src/libcmt-build                         
[libcmt] [ 37%] Performing build step for 'libcmt'                                                                          
[libcmt] [ 50%] Built target cmt                                                                                            
[libcmt] [100%] Built target main                                                                                           
[libcmt] [ 50%] Performing install step for 'libcmt'                                                                        
[libcmt] [ 50%] Built target cmt                                                                                            
[libcmt] [100%] Built target main                                                                                           
[libcmt] Install the project...                                                                                             
[libcmt] -- Install configuration: ""                                                                                       
[libcmt] -- Up-to-date: /tmp/hoge/devel/lib/libcmt.so                                                                       
[libcmt] -- Up-to-date: /tmp/hoge/devel/include/libcmt/CMT.h                                                                
[libcmt] [ 62%] Completed 'libcmt'                                                                                          
[libcmt] [100%] Built target libcmt                                                                                         
[libcmt] <== '/tmp/hoge/build/libcmt/build_env.sh /usr/bin/make --jobserver-fds=3,5 -j' finished with return code '0'       
Finished <== libcmt [ 1.5 seconds ]                                                                                         
[build] Finished.                                                                                                           
[build] Runtime: 1.6 seconds 
k-okada@kokada-t440s:/tmp/hoge$ catkin b -v -i libcmt
==> Expanding alias 'b' from 'catkin b -v -i libcmt' to 'catkin build -v -i libcmt'
----------------------------------------------
Profile:                     default
Extending:          [cached] /opt/ros/indigo
Workspace:                   /tmp/hoge
Source Space:       [exists] /tmp/hoge/src
Build Space:        [exists] /tmp/hoge/build
Devel Space:        [exists] /tmp/hoge/devel
Install Space:     [missing] /tmp/hoge/install
DESTDIR:                     None
----------------------------------------------
Isolate Develspaces:         False
Install Packages:            False
Isolate Installs:            False
----------------------------------------------
Additional CMake Args:       None
Additional Make Args:        None
Additional catkin Make Args: None
Internal Make Job Server:    True
----------------------------------------------
Whitelisted Packages:        None
Blacklisted Packages:        None
----------------------------------------------
Workspace configuration appears valid.
---------------------------------------------- 
Found '20' packages in 0.0 seconds. 
Starting ==> libcmt                                                                                                         
[libcmt] ==> '/tmp/hoge/build/libcmt/build_env.sh /usr/bin/make cmake_check_build_system' in '/tmp/hoge/build/libcmt'       
[libcmt] <== '/tmp/hoge/build/libcmt/build_env.sh /usr/bin/make cmake_check_build_system' finished with return code '0'     
[libcmt] ==> '/tmp/hoge/build/libcmt/build_env.sh /usr/bin/make --jobserver-fds=3,5 -j' in '/tmp/hoge/build/libcmt'         
[libcmt] [ 12%] Performing update step for 'libcmt'                                                                         
[libcmt] Already on 'add-make-install'                                                                                      
[libcmt] Your branch is up-to-date with 'origin/add-make-install'.                                                          
[libcmt] [ 25%] Performing configure step for 'libcmt'                                                                      
[libcmt] -- Configuring done                                                                                                
[libcmt] -- Generating done                                                                                                 
[libcmt] -- Build files have been written to: /tmp/hoge/build/libcmt/libcmt-prefix/src/libcmt-build                         
[libcmt] [ 37%] Performing build step for 'libcmt'                                                                          
[libcmt] [ 50%] Built target cmt                                                                                            
[libcmt] [100%] Built target main                                                                                           
[libcmt] [ 50%] Performing install step for 'libcmt'                                                                        
[libcmt] [ 50%] Built target cmt                                                                                            
[libcmt] [100%] Built target main                                                                                           
[libcmt] Install the project...                                                                                             
[libcmt] -- Install configuration: ""                                                                                       
[libcmt] -- Up-to-date: /tmp/hoge/devel/lib/libcmt.so                                                                       
[libcmt] -- Up-to-date: /tmp/hoge/devel/include/libcmt/CMT.h                                                                
[libcmt] [ 62%] Completed 'libcmt'                                                                                          
[libcmt] [100%] Built target libcmt                                                                                         
[libcmt] <== '/tmp/hoge/build/libcmt/build_env.sh /usr/bin/make --jobserver-fds=3,5 -j' finished with return code '0'       
Finished <== libcmt [ 1.5 seconds ]                                                                                         
[build] Finished.                                                                                                           
[build] Runtime: 1.5 seconds 
k-okada@kokada-t440s:/tmp/hoge$ 
```

**Comment by aginika** [comment]
@k-okada 
Thank you!! That seemed to be remain of build directory. After I remove the directory and do it again, everythings works well!

**Comment by garaemon** [comment]
```
E: Unable to locate package ros-jade-rosbash
E: Unable to locate package ros-jade-rospack
```

**Comment by garaemon** [comment]
merge origin/master may solve this issue

**Comment by aginika** [comment]
I merged from the orgin/master

**Comment by garaemon** [comment]
merged. The test fails because of  sourceforge down.

**Comment by k-okada** [comment]
Errored on debbuild -> http://jenkins.ros.org/job/ros-indigo-libcmt_binarydeb_saucy_amd64/20/console

**Comment by garaemon** [comment]
```
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi && \
	dh_auto_configure -- \
		-DCATKIN_BUILD_BINARY_PACKAGE="1" \
		-DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
		-DCMAKE_PREFIX_PATH="/opt/ros/indigo"
	mkdir -p obj-x86_64-linux-gnu
	cd obj-x86_64-linux-gnu
	cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCATKIN_BUILD_BINARY_PACKAGE=1 -DCMAKE_INSTALL_PREFIX=/opt/ros/indigo -DCMAKE_PREFIX_PATH=/opt/ros/indigo
-- The C compiler identification is GNU 4.8.1
-- The CXX compiler identification is GNU 4.8.1
-- Check for working C compiler: /usr/lib/ccache/cc
-- Check for working C compiler: /usr/lib/ccache/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/lib/ccache/c++
-- Check for working CXX compiler: /usr/lib/ccache/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Using CATKIN_DEVEL_PREFIX: /tmp/buildd/ros-indigo-libcmt-2.0.4-1saucy-20150819-1655/obj-x86_64-linux-gnu/devel
-- Using CMAKE_PREFIX_PATH: /opt/ros/indigo
-- This workspace overlays: /opt/ros/indigo
-- Found PythonInterp: /usr/bin/python (found version "2.7.5") 
-- Using PYTHON_EXECUTABLE: /usr/bin/python
-- Using Debian Python package layout
-- Using empy: /usr/bin/empy
-- Using CATKIN_ENABLE_TESTING: ON
-- Skip enable_testing() when building binary package
-- Using CATKIN_TEST_RESULTS_DIR: /tmp/buildd/ros-indigo-libcmt-2.0.4-1saucy-20150819-1655/obj-x86_64-linux-gnu/test_results
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found gtest sources under '/usr/src/gtest': gtests will be built
-- Using Python nosetests: /usr/bin/nosetests-2.7
-- catkin 0.6.14
-- Could NOT find Git (missing:  GIT_EXECUTABLE) 
CMake Error at /usr/share/cmake-2.8/Modules/ExternalProject.cmake:1269 (message):
  error: could not find git for clone of libcmt
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/ExternalProject.cmake:1797 (_ep_add_download_command)
  CMakeLists.txt:12 (ExternalProject_Add)

```

**Comment by garaemon** [comment]
@aginika any progress on build error on rosbuild farm?

**Comment by aginika** [comment]
Sorry, I will check.

**Comment by aginika** [comment]
I tested on my environment in both hydro and indigo, but I couldn't reproduce this error...

**Comment by k-okada** [comment]
add git to package.xml

--
◉ Kei Okada

**Pull request merged**
