### PR TITLE
voice_text: support dynamic linking

### PR DESCRIPTION
**Pull request by furushchev**
- dynamically link voice_text library
- play error sound if the library cannot be linked
- added test code

### CODE REVIEW

**Comment by furushchev** [comment]
Confirmed that it works on:
- a computer where `voice_text` is installed
- a computer where `voice_text` is **NOT** installed

**Comment by k-okada** [comment]
why you need this?

**Comment by furushchev** [comment]
@k-okada I expect this PR adds a support using this package when installed via `apt-get`.

**Comment by k-okada** [comment]
please see https://github.com/k-okada/jsk_3rdparty/tree/master/3rdparty/voice_text for another example.
This pr has nice implementation, but at the same time, use simple technique and try to increase the number of user who can fix when we have problems in future is also good view point.

**Comment by furushchev** [comment]
@k-okada I totally agree with you keeping things simple. Please create another pull request so to link to this PR when you have time. :+1:

**Comment by k-okada** [comment]
Created #135, I think everyone can create PR from other's branch....

--
◉ Kei Okada


2018-04-02 22:45 GMT+09:00 Yuki Furuta <notifications@github.com>:

**Comment by furushchev** [comment]
@k-okada Sorry, I didn't know that we can create PRs from others' branches. Anyway thank you very much!

**Pull request closed without merging**
