### PR TITLE
[respeaker_ros] fix default sound_play action name of speech_to_text.py

### PR DESCRIPTION
**Pull request by sktometometo**
Fix default sound_play action name of speech_to_text.py.
By this pr, sample_respeaker.launch will work correctly.

### CODE REVIEW

**Comment by pazeshun** [comment]
@sktometometo You should investigate & describe why this can be considered as a mistake.
Otherwise, you may overlook a special reason of this.

In this case, on the basis of my investigation, I'm for your thought that this is just a mistake.
Before #168 , default speaking action name was `sound_play`, and this was changed to `['robotsound', 'robotsound_jp']` on #168 .
And #170 tried to revert this change, but #170 changed the name to `soundplay`, not `sound_play`.
So I concluded that `soundplay` is just a typo of #170 .

**Comment by pazeshun** [comment]
@k-okada Could you review this? I think this PR fixes a typo introduced by #170 .
If you have any special reason for `soundplay`, please tell us.

**Review by pazeshun — APPROVED** [review]

**Comment by knorth55** [comment]
FYI: i investigated and this default parameter change does not affect to PR2 or Fetch.

**Comment by k-okada** [comment]
sorry, this is my mistake...

**Pull request merged**
