### PR TITLE
[develop/fetch] Rebase master request

### PR DESCRIPTION
**Pull request by mqcmd196**
For adopting current origin/master to origin/develop/fetch
- Enable Google NLP
- Support dialogflow noetic

### CODE REVIEW

**Comment by sktometometo** [comment]
Please add description to this PR.

**Comment by mqcmd196** [comment]
edited

**Comment by knorth55** [comment]
Thank you for the request. I rebased now.

**Comment by mqcmd196** [comment]
Thank you!

**Pull request merged**
