### PR TITLE
Fix libcmt with #25 and #26

### PR DESCRIPTION
**Pull request by garaemon**

### CODE REVIEW

**Comment by garaemon** [comment]
hmm, test on jenkins exceeds 50 minutes.

**Comment by garaemon** [comment]
Finally, I found that downward is the problem

**Comment by garaemon** [comment]
Downloading tarball takes so much time on jenkins.
```
$ wget https://github.com/jsk-ros-pkg/archives/raw/master/Fast-Downward-f33d3b65601f.tar.gz
 7% [==>                                    ] 1,073,152   6.23K/s  eta 16m 3s  
```

**Comment by garaemon** [comment]
hmm, git clone is faster than wget.
```
$ time git clone  https://github.com/jsk-ros-pkg/archives
Cloning into 'archives'...
remote: Counting objects: 24, done.
remote: Total 24 (delta 0), reused 0 (delta 0), pack-reused 24
Unpacking objects: 100% (24/24), done.

real	0m29.269s
user	0m22.600s
sys	0m2.740s
```

**Comment by garaemon** [comment]
Finally fixed.
I don't know why but downloading file on github from jenkin takes so much time.
Using [rawgit](https://rawgit.com/) CDN server solved this issue.

**Comment by k-okada** [comment]
It seems if you downloading multiple times in short period, github.com
slowdown the network.

```
lokada@jenkins:~$ wget
https://github.com/jsk-ros-pkg/archives/raw/master/Fast-Downward-f33d3b65601f.tar.gz
--2015-09-28 09:18:12--
https://github.com/jsk-ros-pkg/archives/raw/master/Fast-Downward-f33d3b65601f.tar.gz
Resolving github.com (github.com)... 192.30.252.130
Connecting to github.com (github.com)|192.30.252.130|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location:
https://raw.githubusercontent.com/jsk-ros-pkg/archives/master/Fast-Downward-f33d3b65601f.tar.gz
[following]
--2015-09-28 09:18:12--
https://raw.githubusercontent.com/jsk-ros-pkg/archives/master/Fast-Downward-f33d3b65601f.tar.gz
Resolving raw.githubusercontent.com (raw.githubusercontent.com)...
103.245.222.133
Connecting to raw.githubusercontent.com
(raw.githubusercontent.com)|103.245.222.133|:443...
connected.
HTTP request sent, awaiting response... 200 OK
Length: 13421646 (13M) [application/octet-stream]
Saving to: `Fast-Downward-f33d3b65601f.tar.gz'

17% [============>
         ] 2,350,488    965K/s
```


--
◉ Kei Okada

**Comment by garaemon** [comment]
> It seems if you downloading multiple times in short period, github.com
> slowdown the network.

Yeah, [rawgit](https://rawgit.com/) is a good to solve this issue.

**Comment by garaemon** [comment]
http://jenkins.ros.org/view/IbinS32/job/ros-indigo-libcmt_binarydeb_saucy_i386/63/console
passed

**Pull request merged**
