### PR TITLE
[WIP] Merge Fetch15 branch

### PR DESCRIPTION
**Pull request by knorth55**
this branch is fetch15 and fetch1075's internal branch.
this PR includes these PRs.

- [x] #242
- [x] #249
- [x] #260
- [x] #277
- [x] #279
- [ ] #291
- [ ] #292
- [x] #298
- [x] #300 
- [ ] #323 
- [ ] #337
- [x] #343
- [ ] #350 
- [ ] #375 

cc. @mqcmd196 @708yamaguchi @sktometometo

### CODE REVIEW

**Comment by knorth55** [comment]
Because of conflict, I removed #296 and #323 temporary.
@mqcmd196 please make a goal and complete #296 and #323.
if you want to do new thing, it is better to make a new PR based on #323, not appending #323.

**Comment by knorth55** [comment]
@tkmtnt7000
is this commit included in some PR? if not, please open a PR.
[jsk-ros-pkg/jsk_3rdparty@`8584b81` (#256)](https://github.com/jsk-ros-pkg/jsk_3rdparty/pull/256/commits/8584b81f41fd9f5392f0c7ca256644573bcebbfe)

**Comment by tkmtnt7000** [comment]
Thank you. I made PR https://github.com/jsk-ros-pkg/jsk_3rdparty/pull/378

**Comment by knorth55** [comment]
this PR is moved to #381

**Pull request closed without merging**
