### PR TITLE
add zdepth and zdepth_image_transport package

### PR DESCRIPTION
**Pull request by knorth55**
Zdepth is a depth compression method with zstd library.
This PR adds `zdepth_image_transport` for faster and lighter depth compression.

Zdepth:  https://github.com/catid/Zdepth

- [x] add zdepth package
- [x] add zdepth_image_transport package

### Zdepth

With Zdepth, we can get 30Hz rgb and 30Hz Zdepth.
~Zdepth's decompression is 7Hz, so the visualization seems a bit slow, but faster than compressedDepth (png).~
Now we got 30Hz for decompression, too.

Left: Original, Right: compressed -> decompressed

https://user-images.githubusercontent.com/9300063/199556928-821fe403-f63a-456a-a633-a407bf5fe384.mp4

### CompressedDepth (png)

Because compression of png is so slow, it causes slow down for other depth topics.
(image_transport is serial process, and if one compression is slow, others will be slow down).
The compression is 4Hz, so the raw depth is also 4Hz.
and the decompression is 4Hz.
Ofcourse, we can make it faster with lower png_level, but the compression will be worse.

Left: Original, Right: compressed -> decompressed

https://user-images.githubusercontent.com/9300063/199556980-136d74a3-0a09-4df1-9e8e-354b7b65463f.mp4

## How to try

```
roslaunch openni2 openni2.launch
rosrun image_transport republish zdepth in:=/camera/depth/image_raw raw out:=/camera/depth_decompressed/image_raw raw
```

## Topic size comparison

- ZDepth: `<array type: uint8, length: 35006>`
- compressedDepth (png): `<array type: uint8, length: 61084>`

- Original: `<array type: uint8, length: 614400>`

### Compression

- ZDepth

```
$ rostopic hz /camera/depth/image_raw/zdepth
subscribed to [/camera/depth/image_raw/zdepth]
average rate: 29.973
        min: 0.033s max: 0.034s std dev: 0.00010s window: 17
```

- Compressed Depth (png)
```
$ rostopic hz /camera/depth/image_raw/compressedDepth
subscribed to [/camera/depth/image_raw/compressedDepth]
average rate: 4.155
        min: 0.241s max: 0.241s std dev: 0.00000s window: 2
```

### Decompression

- Zdepth

```
$ rostopic hz /camera/depth/image_raw/zdepth
subscribed to [/camera/depth/image_raw/zdepth]
average rate: 29.609
        min: 0.013s max: 0.044s std dev: 0.00686s window: 29

```

- Compressed Depth (png)

```
$ rostopic hz /camera/depth_decompressed/image_raw
subscribed to [/camera/depth_decompressed/image_raw]
average rate: 4.175
        min: 0.233s max: 0.244s std dev: 0.00462s window: 4
```

### CODE REVIEW

**Comment by knorth55** [comment]
Now I finished workin on this PR! I made Zdepth image transport! :)

## Visualize

### Zdepth

With Zdepth, we can get 30Hz rgb and 30Hz Zdepth.
Zdepth's decompression is 7Hz, so the visualization seems a bit slow, but faster than compressedDepth (png).

https://user-images.githubusercontent.com/9300063/199546795-cd57ef3e-7cc8-4d96-a309-55a333853e81.mp4

### CompressedDepth (png)

Because compression of png is so slow, it causes slow down for other RGB topics.
(image_transport is serial process, and if one compression is slow, others will be slow down).
The compression is 4Hz, so the RBG is also 4Hz.
and the decompression is 4Hz.

https://user-images.githubusercontent.com/9300063/199546769-88bcdfad-50d1-4aa8-a4d7-bf19579555bd.mp4

## How to try

```
roslaunch openni2 openni2.launch
rosrun image_transport republish zdepth in:=/camera/depth/image_raw raw out:=/camera/depth_decompressed/image_raw raw
```

## Topic size comparison

- ZDepth: `<array type: uint8, length: 41672>`
- compressedDepth (png): `<array type: uint8, length: 61084>`

- Original: `<array type: uint8, length: 614400>`

## Frequency Comparison

### Compression

- ZDepth

```
$ rostopic hz /camera/depth/image_raw/zdepth
subscribed to [/camera/depth/image_raw/zdepth]
average rate: 29.973
        min: 0.033s max: 0.034s std dev: 0.00010s window: 17
```

- Compressed Depth (png)
```
$ rostopic hz /camera/depth/image_raw/compressedDepth
subscribed to [/camera/depth/image_raw/compressedDepth]
average rate: 4.155
        min: 0.241s max: 0.241s std dev: 0.00000s window: 2
```

### Decompression

- Zdepth

```
$ rostopic hz /camera/depth_decompressed/image_raw
subscribed to [/camera/depth_decompressed/image_raw]
average rate: 7.030
        min: 0.138s max: 0.148s std dev: 0.00404s window: 6
```

- Compressed Depth (png)

```
$ rostopic hz /camera/depth_decompressed/image_raw
subscribed to [/camera/depth_decompressed/image_raw]
average rate: 4.175
        min: 0.233s max: 0.244s std dev: 0.00462s window: 4
```

**Comment by knorth55** [comment]
My implementation was bad. bottleneck was memory copy.
I speed up and now I got 30Hz for decompression!!
Actually, it only takes `2ms`, so we can use faster depth camera.

### Visualize

Left: Original, Right: compressed -> decompressed

https://user-images.githubusercontent.com/9300063/199555971-1c25d299-f889-437d-8c99-a767fd22e346.mp4


### Data length
data: "<array type: uint8, length: 35006>"

### Compression

```
$ rostopic hz /camera/depth/image_raw/zdepth
subscribed to [/camera/depth/image_raw/zdepth]
average rate: 29.609
        min: 0.013s max: 0.044s std dev: 0.00686s window: 29

```

### Decompression
```
$ rostopic hz /camera/depth_decompressed/image_raw
subscribed to [/camera/depth_decompressed/image_raw]
average rate: 29.749
        min: 0.020s max: 0.044s std dev: 0.00344s window: 28
```

**Comment by k-okada** [comment]
please add depends to `jsk_3rdparty/package.xml` if there is other packages thas did not listed on meta package, pelase createa different PR. https://github.com/jsk-ros-pkg/jsk_3rdparty/pull/406/files#diff-defb64385d3c32863acebd02aefed71ba001d55f2bb191c94a87d9ec96da6b8a

**Comment by knorth55** [comment]
i add `zdepth` and `zdepth_image_transport` in `jsk_3rdparty/package.xml`.

> if there is other packages thas did not listed on meta package, pelase createa different PR.

I will.

**Comment by knorth55** [comment]
@k-okada I made a PR https://github.com/jsk-ros-pkg/jsk_3rdparty/pull/424

**Review by k-okada — CHANGES_REQUESTED** [review]
test failed on 16.04, it seems `GIT_TAG` and `GIT_SHALOW` did not work. Not sure about exact reason. The document say https://cmake.org/cmake/help/latest/module/ExternalProject.html
```
If GIT_SHALLOW is enabled then GIT_TAG works only with branch names and tags. A commit hash is not allowed.

Note that if not provided, GIT_TAG defaults to master, not the default Git branch name.
```

remove `GIT_SHALLOW` or skip build zdepth before 16.04 or based on  CMake/git  version.

**Comment by knorth55** [comment]
In Kinectic, this package cannot be built, so I stopped building in kinetic and below.

**Pull request merged**
