### PR TITLE
[voice_text] Support other speakers than SAYAKA and new directory tree

### PR DESCRIPTION
**Pull request by pazeshun**
We bought a new VoiceText SDK whose speaker is RISA and tried to use voice_text package with that SDK.
However, current voice_text assumes that the speaker is SAYAKA:
https://github.com/jsk-ros-pkg/jsk_3rdparty/blob/bfce3ffc368bfb9367bd429a289aee36c1bbc0d2/3rdparty/voice_text/CMakeLists.txt#L28
https://github.com/jsk-ros-pkg/jsk_3rdparty/blob/bfce3ffc368bfb9367bd429a289aee36c1bbc0d2/3rdparty/voice_text/src/voice_text.cpp#L24
https://github.com/jsk-ros-pkg/jsk_3rdparty/blob/bfce3ffc368bfb9367bd429a289aee36c1bbc0d2/3rdparty/voice_text/src/voice_text.cpp#L35
https://github.com/jsk-ros-pkg/jsk_3rdparty/blob/bfce3ffc368bfb9367bd429a289aee36c1bbc0d2/3rdparty/voice_text/launch/voice_text.launch#L16
In addition, the new VoiceText SDK has a different directory tree from the old one (e.g., `/usr/vt/<SPEAKER>/<NUMBER>/bin/x86_64/RAMIO/libvt_jpn.so` was moved to `/usr/vt/<SPEAKER>/<NUMBER>/bin/LINUX64_GLIBC3/RAMIO/libvt_jpn.so`).

This PR enables to support other speakers than SAYAKA and the new directory tree.
The old directory tree remains supported.

cc. @MiyabiTane @knorth55

### CODE REVIEW

**Comment by pazeshun** [comment]
This PR is now being tested on hirovision (ROS PC for hiro014)

**Comment by pazeshun** [comment]
This PR is now being tested on PR2 and Fetch (SAYAKA, old directory tree)

**Comment by knorth55** [comment]
This works with baxter, too!
Quite good PR.

**Review by knorth55 — APPROVED** [review]

**Comment by pazeshun** [comment]
Thank you!

**Pull request merged**
