### PR TITLE
Add args to ros_speech_recognition

### PR DESCRIPTION
**Pull request by 708yamaguchi**
In this pull request , I did followings:
- Update README about installation and missing rosparam description
- Add args of `speech_recognition.launch` to use more variety of microphones (main of this PR)
- Add test for this package. (rosbag file for the test is copied from `respeaker_ros`)

However, I am wondering that there is `speech_to_text.py` in `respeaker_ros` package.
https://github.com/jsk-ros-pkg/jsk_3rdparty/blob/master/respeaker_ros/scripts/speech_to_text.py
If `respeaker_ros` is expected to be independent of `ros_speech_recognition`, I think this is OK.

In this case, is it safe to have duplicated rosbag files in `respeaker_ros` and `ros_speech_recognition`?
If there is any better solution, I will follow that. 
Thank you.

### CODE REVIEW

**Comment by 708yamaguchi** [comment]
Thank you very much for your advice.

#### About catkin_virtualenv
I understand `catkin_virtualenv` to some extent and use it.
Now, in my workspace, `speech_recognition_node.py` is executed under `venv`
```bash
$ cat $(catkin_find ros_speech_recognition speech_recognition_node.py) 
#!/usr/bin/env bash
/home/naoya/ros/melodic/devel/.private/ros_speech_recognition/share/ros_speech_recognition/venv/bin/python /home/naoya/ros/melodic/src/jsk-ros-pkg/jsk_3rdparty/ros_speech_recognition/scripts/speech_recognition_node.py "$@"
```

#### About test error
I found another problem. The test I added was actually not executed (this error somtimes occurs in `respeaker_ros` package, too).
I think this is because `rospy.sleep` in `test_topic_published.py` died when `ROSTimeMovedBackwardsException` occured in `rosbag play`.
To avoid this kind of error, I remove `--clock` from `rosbag play` and remove `use_sim_time: true`.
I am not sure whether this is right solution, so could you please let me know your idea?

https://api.travis-ci.org/v3/job/679173232/log.txt

```bash
[ros_speech_recognition:make]  * TESTS: 0
[ros_speech_recognition:make]  * ERRORS: 0
[ros_speech_recognition:make]  * FAILURES: 0
```

```bash
[ros_speech_recognition:make] Traceback (most recent call last):
[ros_speech_recognition:make]   File "/opt/ros/kinetic/share/jsk_tools/src/test_topic_published.py", line 102, in <module>
[ros_speech_recognition:make]     rostest.run(PKG, NAME, TestTopicPublished, sys.argv)
[ros_speech_recognition:make]   File "/opt/ros/kinetic/lib/python2.7/dist-packages/rostest/__init__.py", line 146, in rosrun
[ros_speech_recognition:make]     result = rosunit.create_xml_runner(package, test_name, result_file).run(suite)
[ros_speech_recognition:make]   File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosunit/xmlrunner.py", line 262, in run
[ros_speech_recognition:make]     test(result)
[ros_speech_recognition:make]   File "/usr/lib/python2.7/unittest/suite.py", line 70, in __call__
[ros_speech_recognition:make]     return self.run(*args, **kwds)
[ros_speech_recognition:make]   File "/usr/lib/python2.7/unittest/suite.py", line 108, in run
[ros_speech_recognition:make]     test(result)
[ros_speech_recognition:make]   File "/usr/lib/python2.7/unittest/case.py", line 393, in __call__
[ros_speech_recognition:make]     return self.run(*args, **kwds)
[ros_speech_recognition:make]   File "/usr/lib/python2.7/unittest/case.py", line 329, in run
[ros_speech_recognition:make]     testMethod()
[ros_speech_recognition:make]   File "/opt/ros/kinetic/share/jsk_tools/src/test_topic_published.py", line 97, in test_published
[ros_speech_recognition:make]     rospy.sleep(0.01)
[ros_speech_recognition:make]   File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/timer.py", line 164, in sleep
[ros_speech_recognition:make]     raise rospy.exceptions.ROSTimeMovedBackwardsException(time_jump)
[ros_speech_recognition:make] rospy.exceptions.ROSTimeMovedBackwardsException: ROS time moved backwards
```

**Comment by 708yamaguchi** [comment]
test with `DOCKER_IMAGE=i386/ubuntu16.04` fails maybe because `flac` package is not installed.

```bash
[ros_speech_recognition:make]   File "/usr/local/lib/python2.7/dist-packages/speech_recognition/__init__.py", line 457, in get_flac_data                                                                                
[ros_speech_recognition:make]     ], stdin=subprocess.PIPE, stdout=subprocess.PIPE, startupinfo=startup_info)                                                                                
[ros_speech_recognition:make]   File "/usr/lib/python2.7/subprocess.py", line 711, in __init__                                                                                
[ros_speech_recognition:make]     errread, errwrite)                                                                                
[ros_speech_recognition:make]   File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child                                                                                
[ros_speech_recognition:make]     raise child_exception                                                                                
[ros_speech_recognition:make] OSError: [Errno 2] No such file or directory
```

In my docker `i386/ubuntu16.04` environment, test successfully finish after `sudo apt install flac`

**Comment by k-okada** [comment]
> To avoid this kind of error, I remove --clock from rosbag play and remove
use_sim_time: true.

I think that wood be ok.

> test with DOCKER_IMAGE=i386/ubuntu16.04 fails maybe because flac package
is not installed.
add flac to rosdistro/rosdep/base.yaml and add them to package.xml

--
◉ Kei Okada



2020年4月26日(日) 5:05 Naoya Yamaguchi <notifications@github.com>:

**Comment by 708yamaguchi** [comment]
Thank you for your advice!

I created pull request to ros/rosdistro and add `flac` as run_depend in this repository.
https://github.com/ros/rosdistro/pull/24600

Please merge this pull request after above is merged.

**Comment by 708yamaguchi** [comment]
Additional information:
The below error occurs because we try to call `flac-linux-x86_64` executable in `i386`.
```
[ros_speech_recognition:make] OSError: [Errno 2] No such file or directory
```

This happens because `i386` docker environment returns `x86_64` architecture by ` python -c "import platform; print(platform.machine())"` and therefore `flac_converter` variable has `/usr/local/lib/python2.7/dist-packages/speech_recognition/flac-linux-x86_64`
https://github.com/Uberi/speech_recognition/blob/c89856088ad81d81d38be314e3db50905481c5fe/speech_recognition/__init__.py#L1395-L1410

**Comment by 708yamaguchi** [comment]
Now, https://github.com/ros/rosdistro/pull/24600 is merged, so I close / reopen pull request and  restart travis test.
https://travis-ci.org/github/jsk-ros-pkg/jsk_3rdparty/builds/681751239

**Comment by 708yamaguchi** [comment]
Travis test passed, but some of tests in `respeaker_ros` is not done because of the  `ROSTimeMovedBackwardsException` problem (the same problem as mentioned above).
https://travis-ci.org/github/jsk-ros-pkg/jsk_3rdparty/builds/681751239
https://api.travis-ci.org/v3/job/681751240/log.txt
```
[respeaker_ros:make]   File "/opt/ros/indigo/share/jsk_tools/src/test_topic_published.py", line 102, in <module>                                                                             
[respeaker_ros:make] [31m[ERROR] [WallTime: 1588296975.540422] [1559642913.589570] ROS time moved backwards: 10.293723236s                                                                             
[respeaker_ros:make] [0m[31m[ERROR] [WallTime: 1588296975.541689] [1559642913.589570] ROS time moved backwards: 10.273579437s                                                                             
[respeaker_ros:make] [0m[31m[ERROR] [WallTime: 1588296975.542149] [1559642913.589570] ROS time moved backwards: 9.61909619s                                                                             
[respeaker_ros:make] [0m    rostest.run(PKG, NAME, TestTopicPublished, sys.argv)                                                                             
[respeaker_ros:make]   File "/opt/ros/indigo/lib/python2.7/dist-packages/rostest/__init__.py", line 146, in rosrun                                                                             
[respeaker_ros:make] Exception in thread Thread-7:                                                                             
[respeaker_ros:make] Traceback (most recent call last):                                                                             
[respeaker_ros:make]   File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner                                                                             
[respeaker_ros:make]     self.run()                                                                             
[respeaker_ros:make]   File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/timer.py", line 214, in run                                                                             
[respeaker_ros:make]     r.sleep()                                                                             
[respeaker_ros:make]   File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/timer.py", line 99, in sleep                                                                             
[respeaker_ros:make]     sleep(self._remaining(curr_time))                                                                             
[respeaker_ros:make]   File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/timer.py", line 155, in sleep                                                                             
[respeaker_ros:make]     raise rospy.exceptions.ROSTimeMovedBackwardsException(time_jump)                                                                             
[respeaker_ros:make] ROSTimeMovedBackwardsException: ROS time moved backwards      

...

[respeaker_ros:make] [32m * RESULT: SUCCESS[0m                           
[respeaker_ros:make]  * TESTS: 0                           
[respeaker_ros:make]  * ERRORS: 0                           
[respeaker_ros:make]  * FAILURES: 0
```

I pushed additional commit to remove `--clock` and `use_sim=True` from `respeaker_ros` test.
Also, I add `flac` to run_depend in `respeaker_ros`

**Comment by 708yamaguchi** [comment]
In the all 4 test cases, `respeaker_ros` test and `ros_speech_recognition` test were executed and passed properly.
``` 
[respeaker_ros:make] [32m * RESULT: SUCCESS[0m
[respeaker_ros:make]  * TESTS: 1
[respeaker_ros:make]  * ERRORS: 0
[respeaker_ros:make]  * FAILURES: 0

~~~

[ros_speech_recognition:make] [32m * RESULT: SUCCESS[0m
[ros_speech_recognition:make]  * TESTS: 1
[ros_speech_recognition:make]  * ERRORS: 0
[ros_speech_recognition:make]  * FAILURES: 0
```

I think it's OK to be merged.

**Pull request merged**
