### PR TITLE
[ros_ speech_recognition] update default arg for speech_recognition.launch

### PR DESCRIPTION
**Pull request by knorth55**
this PR changes the default value for `speech_recognition.launch`.
with this change, speech_recognition.launch automatically starts and recognized results are published in /speech_to_text topic.

without this PR, we need to run `rosservice call /~~~` to start `speech_recognition` node and the output topic is published in `/Tablet/voice`.

### CODE REVIEW

**Review by pazeshun — CHANGES_REQUESTED** [review]
Maybe README should also be fixed.
(Also, there may be other doc)

**Comment by knorth55** [comment]
I update the readme.

**Comment by k-okada** [comment]
humm, why we can find `restart failed job` button.... https://docs.github.com/en/actions/managing-workflow-runs/re-running-workflows-and-jobs

Screenshot from 2023-01-25 10-29-30

**Comment by knorth55** [comment]
@k-okada 
> humm, why we can find restart failed job button.... [docs.github.com/en/actions/managing-workflow-runs/re-running-workflows-and-jobs](https://docs.github.com/en/actions/managing-workflow-runs/re-running-workflows-and-jobs)

The button will appear when all the jobs are finished.
When some jobs are running, the button does not appear.

**Pull request merged**
