### PR TITLE
Fix issues in respeaker_node

### PR DESCRIPTION
**Pull request by dgorissen**
Fixed a number of issues in respeaker_node.py. Now runs without error for me with python 3.7.10.

### CODE REVIEW

**Comment by 708yamaguchi** [comment]
Thank you very much for your contribution.
There are a few things I would like to see fixed.

- Keeping Python2.x compatibility

Please keep Python2.x compatibility, because the system python version of melodic and older distro is 2.x.
I try your PR with Python2.7, I got the following error.

```
Traceback (most recent call last):
  File "/home/fetch/ros/melodic/src/jsk-ros-pkg/jsk_3rdparty/respeaker_ros/scripts/respeaker_node.py", line 432, in <module>
    n = RespeakerNode()
  File "/home/fetch/ros/melodic/src/jsk-ros-pkg/jsk_3rdparty/respeaker_ros/scripts/respeaker_node.py", line 325, in __init__
    self.dyn_srv = Server(RespeakerConfig, self.on_config)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/server.py", line 81, in __init__
    self._change_config(self.config, ~0)  # Consistent with the C++ API, the callback gets called with level=~0 (i.e. -1)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/server.py", line 104, in _change_config
    self.config = self.callback(config, level)
  File "/home/fetch/ros/melodic/src/jsk-ros-pkg/jsk_3rdparty/respeaker_ros/scripts/respeaker_node.py", line 355, in on_config
    config[name] = self.respeaker.read(name)
  File "/home/fetch/ros/melodic/src/jsk-ros-pkg/jsk_3rdparty/respeaker_ros/scripts/respeaker_node.py", line 176, in read
    response = struct.unpack(b'ii', response.tobytes())
AttributeError: 'array.array' object has no attribute 'tobytes'
[respeaker_node-72] process has died [pid 23852, exit code 1, cmd /home/fetch/ros/melodic/src/jsk-ros-pkg/jsk_3rdparty/respeaker_ros/scripts/respeaker_node.py __name:=respeaker_node __log:=/home/fetch/.ros/log/7a5058ec-146b-11ec-b3d8-3947284f3202/respeaker_node-72.log].
log file: /home/fetch/.ros/log/7a5058ec-146b-11ec-b3d8-3947284f3202/respeaker_node-72*.log
```

I think `sys.version_info` is one of the solution.
https://github.com/jsk-ros-pkg/jsk_3rdparty/blob/27767817252febb8322a291be36042bc5c51c76f/julius_ros/src/julius_ros/transport.py#L49-L50

- Fixing the default value

Changing the default value may cause the current `respeaker_ros` programs to stop working.
Please do not change the default value.
https://github.com/jsk-ros-pkg/jsk_3rdparty/pull/283/files#diff-7155cdcc8bb27a7ee65e5f5fc2fcf8c2e041f3e3caea28c1f097e3902e515a94

**Comment by knorth55** [comment]
@708yamaguchi can you make a refined version of this PR?
this PR is for noetic, probably.

**Comment by 708yamaguchi** [comment]
@dgorissen 

I created PR which is compatible with Python 2.x.
https://github.com/jsk-ros-pkg/jsk_3rdparty/pull/284

Could you check this PR with following command?
```
roslaunch respeaker_ros sample_respeaker.launch language:=en-GB self_cancellation:=false
```

**Comment by dgorissen** [comment]
Thank you @knorth55 @708yamaguchi   This works for me. I just point out that there is a second usage of `tobytes()` in `stream_callback(..)` that also needs the python version guard.

**Comment by 708yamaguchi** [comment]
@dgorissen 

Thank you for your checking.

> I just point out that there is a second usage of tobytes() in stream_callback(..) that also needs the python version guard.

Does `a second usage of tobytes() in stream_callback(..)` mean [this line](https://github.com/708yamaguchi/jsk_3rdparty/blob/b7514a2abfe7bb5f49dc48fa324606a5580ef1ff/respeaker_ros/scripts/respeaker_node.py#L289) ?

I think we do not need python version gurad here.
This is because `chan_data` is type of `numpy.ndarray` while `response` is type of `array.array`.

`numpy.ndarray.tostring` and `numpy.ndarray.tobytes` are available in both Python 2.x and Python 3.x and they have the same behavior.
https://stackoverflow.com/questions/30167538/convert-a-numpy-ndarray-to-stringor-bytes-and-convert-it-back-to-numpy-ndarray#comment107863140_30167538

**Comment by dgorissen** [comment]
Ah yes, good spot!

**Comment by 708yamaguchi** [comment]
Move this PR to https://github.com/jsk-ros-pkg/jsk_3rdparty/pull/284 

Thank you @dgorissen

**Pull request closed without merging**
