### PR TITLE
[voice_text] Call rosservice from python instead of bash

### PR DESCRIPTION
**Pull request by itohdak**
`rosservice call` with bash command sometimes gets stuck when executed one after another.
Instead of using `rosservice call` with bash command, this PR calls the service through Python node.

### CODE REVIEW

**Comment by itohdak** [comment]
@k-okada I rewrote `text2wave` with python and removed unnecessary files.

**Comment by itohdak** [comment]
The trouble around this is a little bit complex as I commented in #167.

About two weeks ago, @Affonso-Gui and @708yamaguchi told me that the don't-speak issue had been occurring with the Fetch robot too.
So we debugged for the cause and found that the gstreamer issue was occurring.
Since this gstreamer error occurs before the voice_text issue, I think the Fetch robot hasn't experienced the voice_text issue, which will possibly be solved with this PR.
To deal with this gstreamer error, we are now respawning the sound_play node with like [this commit](https://github.com/itohdak/audio_common/commit/c851d83255670b8a5e5f6936aa4fbaacda810fd7#diff-4ae1c2f992d4f4cab6aed7d93d48e5aa), which is a workaround solution.

I'm not sure for the PR2 robot. @knorth55

**Comment by knorth55** [comment]
@itohdak both issue does not happen in PR2.
this PR looks good to me.
But I want to know more about gstreamer issue.
Where are you guys dicussing  about the issue?
which version of gstreamer are you using?
Has you solve the issue on Fetch?

**Comment by itohdak** [comment]
@knorth55 Sorry. We have not discussed online, so I have no link I can show you.

@furushchev first found the gstreamer issue and taught us the workaround.
Actually, the PR was made in https://github.com/ros-drivers/audio_common/pull/77, but it hasn't been merged because of the large amount of changes.
On PR2, I think this developed version is used and, if so, it is reasonable that the gstreamer issue doesn't happen.
The commit in my last comment is the one cherry-picked from @furushchev 's commits.

On Fetch, the gstreamer issue was actually solved with applying this solution.
However, the latest version of sound_play cannot applied for Japanese because of the encoding issue, and it is now pending.
This encoding issue is discussed in https://github.com/ros-drivers/audio_common/pull/123.

My version of gstreamer is as below.
```
$ gst-inspect-1.0 --gst-version
GStreamer Core Library version 1.2.4
```

**Pull request merged**
