### PR TITLE
[libsiftfast] Use PYTHON_INSTALL_DIR to install python module with catkin

### PR DESCRIPTION
**Pull request by wkentaro**
Modified:
  - 3rdparty/libsiftfast/CMakeLists.txt

### CODE REVIEW

**Comment by wkentaro** [comment]
Fixes https://github.com/jsk-ros-pkg/jsk_recognition/issues/1616#issuecomment-214271795

**Comment by wkentaro** [comment]
Closes https://github.com/jsk-ros-pkg/jsk_3rdparty/issues/61

**Comment by k-okada** [comment]
please update to jsk_travis 0.4.5

**Comment by wkentaro** [comment]
Please merge this.

**Pull request merged**
