### PR TITLE
voice_text: support dynamic linking

### PR DESCRIPTION
**Pull request by k-okada**
rewrited version of #131, see https://github.com/jsk-ros-pkg/jsk_3rdparty/pull/131#issuecomment-377932162 for discussion

### CODE REVIEW

**Comment by k-okada** [comment]
@furushchev can you double check if this is ok?

**Comment by furushchev** [comment]
@k-okada It looks you are also working on this... I sent a pull request to https://github.com/k-okada/jsk_3rdparty/pull/2

**Comment by furushchev** [comment]
@k-okada And I would like to do double check, after merging this pull request users will get `voice_text` binary from `apt-get` but still cannot use the functionality since the binary is statically linked to dummy library. Is that ok for you?

**Comment by k-okada** [comment]
dummy install will not included in deb files.
```
k-okada@p51s:/tmp/fduga$ catkin_make install
...
k-okada@p51s:/tmp/fduga$ find install/ | grep lib
install/lib
install/lib/text2wave
install/lib/python2.7
install/lib/python2.7/dist-packages
install/lib/python2.7/dist-packages/voice_text
install/lib/python2.7/dist-packages/voice_text/cfg
install/lib/python2.7/dist-packages/voice_text/cfg/VoiceTextConfig.py
install/lib/python2.7/dist-packages/voice_text/cfg/__init__.pyc
install/lib/python2.7/dist-packages/voice_text/cfg/VoiceTextConfig.pyc
install/lib/python2.7/dist-packages/voice_text/cfg/__init__.py
install/lib/python2.7/dist-packages/voice_text/__init__.pyc
install/lib/python2.7/dist-packages/voice_text/srv
install/lib/python2.7/dist-packages/voice_text/srv/__init__.pyc
install/lib/python2.7/dist-packages/voice_text/srv/_TextToSpeech.py
install/lib/python2.7/dist-packages/voice_text/srv/__init__.py
install/lib/python2.7/dist-packages/voice_text/srv/_TextToSpeech.pyc
install/lib/python2.7/dist-packages/voice_text/__init__.py
install/lib/voice_text
install/lib/voice_text/voice_text
install/lib/pkgconfig
install/lib/pkgconfig/voice_text.pc
k-okada@p51s:/tmp/fduga$ ldd install/lib/voice_text/voice_text | grep vt_j
	libvt_jpn.so => not found

```
but, yes dpkg will not allow such a strange binary...

**Comment by k-okada** [comment]
it will be ok
```
k-okada@p51s:/tmp$ hub clone tork-a/jsk_3rdparty-release
k-okada@p51s:/tmp/jsk_3rdparty-release$ git checkout remotes/origin/debian/kinetic/xenial/voice_text
k-okada@p51s:/tmp/jsk_3rdparty-release$ cp -r ../fduga/src/voice_text/src/* ./src
k-okada@p51s:/tmp/jsk_3rdparty-release$ cp -r ../fduga/src/voice_text/CMakeLists.txt  .
k-okada@p51s:/tmp/jsk_3rdparty-release$ dpkg -x ../ros-kinetic-voice-text_2.1.6-0xenial_amd64.deb  hoge
k-okada@p51s:/tmp/jsk_3rdparty-release$ ldd hoge/opt/ros/kinetic/lib/voice_text/voice_text  | grep jpn
	libvt_jpn.so => not found
```

**Pull request merged**
