### PR TITLE
[collada_urdf_jsk_patch] Depends on catkin-tools

### PR DESCRIPTION
**Pull request by garaemon**

### CODE REVIEW

**Comment by garaemon** [comment]
```
18:32:02 origin	https://github.com/tork-a/jsk_3rdparty-release.git (push)
18:32:03 fatal: could not read Username for 'https://github.com': No such device or address
18:32:03 ROS Distro index file associate with commit 'ec307b7d22720655fec32112fa62430463fce763'[0m
18:32:03 New ROS Distro index url: 'https://raw.githubusercontent.com/ros/rosdistro/ec307b7d22720655fec32112fa62430463fce763/index.yaml'[0m
18:32:03 [32m[1m==> [0m[0mFetching 'jsk_3rdparty' repository from 'https://github.com/tork-a/jsk_3rdparty-release.git'[0m
18:32:03 [32m[1m==> [0mTesting for push permission on release repository[0m[0m
18:32:03 [34m[1m==> [0m[1m[0mgit remote -v[0m
18:32:03 [34m[1m==> [0m[1m[0mgit push --dry-run[0m
18:32:03 [31m[1mCannot push to remote release repository.[0m
18:32:03 Build step 'Execute shell' marked build as failure
```

**Comment by garaemon** [comment]
Jenkins fails to push to tork-a/xx-release repository

**Comment by k-okada** [comment]
every time we rebooted jenkins machine, we have to manually input password
for the fist time, ... I

--
◉ Kei Okada

**Comment by garaemon** [comment]
http://jenkins.ros.org/view/HbinP64/job/ros-hydro-collada-urdf-jsk-patch_binarydeb_precise_amd64/

deb passed

**Pull request merged**
