### PR TITLE
[lpg_planner] automatical download

### PR DESCRIPTION
**Pull request by Naoki-Hiraoka**
To build `lpg_planner`, we have to execute the following commands.
1. Download lpg1.2-linux.tar.gz manually.
2. `catkin build lpg_planner`

With this PR, lpg1.2-linux.tar.gz is automatically downloaded with `catkin build lpg_planner`,
so all you have to do to build `lpg_planner` is only
 1. `catkin build lpg_planner`

### CODE REVIEW

**Comment by Naoki-Hiraoka** [comment]
`lpg_planner` is used here
https://github.com/jsk-ros-pkg/jsk_planning/blob/b99d2a2e27451ae3acb27d11efdd1712977da446/pddl/pddl_planner/demos/2016_kamada_durative/example.launch#L7

**Comment by k-okada** [comment]
@Naoki-Hiraoka thanks for contribution, it seems LPG author want us to registore before download the binary package and I'd like to respect their policy.

chainging to use `externalproject_add` would be good idea.

**Comment by Naoki-Hiraoka** [comment]
https://github.com/jsk-ros-pkg/jsk_3rdparty/pull/204
https://github.com/jsk-ros-pkg/jsk_3rdparty/pull/79

**Comment by knorth55** [comment]
oh, i didn't know this PR.

**Pull request closed without merging**
