### PR TITLE
[rostwitter] install scripts directory in rostwitter

### PR DESCRIPTION
**Pull request by knorth55**
@k-okada I'm sorry.
related to \#285

### CODE REVIEW

**Comment by k-okada** [comment]
```
diff --git a/rostwitter/setup.py b/rostwitter/setup.py
index 0fc0bb58..577ca637 100644
--- a/rostwitter/setup.py
+++ b/rostwitter/setup.py
@@ -7,7 +7,7 @@ from distutils.core import setup
 d = generate_distutils_setup(
     packages=['rostwitter'],
     package_dir={'': 'python'},
-    scripts=['scripts/tweet.py'],
+    scripts=['scripts/tweet.py', 'scripts/tweet_image_server.py'],
 )
 
 setup(**d)

```
?

**Comment by knorth55** [comment]
!
is it better than `catkin_install_python` for noetic migration?

```
diff --git a/rostwitter/CMakeLists.txt b/rostwitter/CMakeLists.txt
index 58958327..3e8b4edc 100644
--- a/rostwitter/CMakeLists.txt
+++ b/rostwitter/CMakeLists.txt
@@ -25,6 +25,17 @@ catkin_package(
   CATKIN_DEPENDS message_runtime
 )
 
-install(PROGRAMS scripts/tweet.py
-  DESTINATION ${CATKIN_PACKAGE_BIN_DESTINATION}
-)
+# on noetic it needs catkin_install_python to support Python3
+# but it does not work on indigo for some reason...
+if($ENV{ROS_DISTRO} STREQUAL "indigo")
+  install(DIRECTORY scripts
+    DESTINATION ${CATKIN_PACKAGE_SHARE_DESTINATION}
+    USE_SOURCE_PERMISSIONS
+  )
+else()
+  file(GLOB SCRIPT_PROGRAMS scripts/*.py)
+  catkin_install_python(
+    PROGRAMS ${SCRIPT_PROGRAMS}
+    DESTINATION ${CATKIN_PACKAGE_SHARE_DESTINATION}/scripts/
+  )
+endif()
```

**Comment by k-okada** [comment]
you're right. Adding script name to `setup.py` just install to global bin directory
```
$ ls install/lib/rostwitter/ install/bin/
install/bin/:
tweet_image_server.py  tweet.py

install/lib/rostwitter/:
tweet.py
```

**Comment by knorth55** [comment]
thank you.
it is good for me to know the difference.

**Comment by k-okada** [comment]
closed with test code #285

**Pull request closed without merging**
