### PR TITLE
[switchbot_ros] add respawn arg in switchbot.launch

### PR DESCRIPTION
**Pull request by knorth55**
this PR adds `respawn` arg in `switchbot.launch`

### CODE REVIEW

**Review by mqcmd196 — APPROVED** [review]

**Comment by k-okada** [comment]
I suppose we need `respawn` because the node sometimes/often terminates. @knorth55 could you provide the error log ? and check if @mqcmd196 fixed it.

**Comment by knorth55** [comment]
when I launch `switchbot.launch` with no internet connection, the server fails with the following error.
Fetch sometimes fail to launch `switchbot`, so we need to catch the following error, or just respawn the node again and again.

```log
$ roslaunch switchbot_ros switchbot.launch token:=hogehoge
... logging to /home/knorth55/.ros/log/570d6c54-fa61-11eb-a4a4-0242fc465144/roslaunch-melodic-p50-17493.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
WARNING: disk usage in log directory [/home/knorth55/.ros/log] is over 1GB.
It's recommended that you use the 'rosclean' command.

started roslaunch server http://melodic-p50:46875/

SUMMARY
========

PARAMETERS
 * /rosdistro: melodic
 * /rosversion: 1.14.11
 * /switchbot_ros/token: hogehoge

NODES
  /
    switchbot_ros (switchbot_ros/switchbot_ros_server.py)

auto-starting new master
process[master]: started with pid [17521]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 570d6c54-fa61-11eb-a4a4-0242fc465144
process[rosout-1]: started with pid [17539]
started core service [/rosout]
process[switchbot_ros-2]: started with pid [17546]
Traceback (most recent call last):
  File "/home/knorth55/ros/melodic/src/jsk-ros-pkg/jsk_3rdparty/switchbot_ros/scripts/switchbot_ros_server.py", line 71, in <module>
    server = SwitchBotAction()
  File "/home/knorth55/ros/melodic/src/jsk-ros-pkg/jsk_3rdparty/switchbot_ros/scripts/switchbot_ros_server.py", line 25, in __init__
    self.bots = SwitchBotAPIClient(token=self.token)
  File "/home/knorth55/ros/melodic/src/jsk-ros-pkg/jsk_3rdparty/switchbot_ros/scripts/switchbot.py", line 22, in __init__
    self.update_device_list()
  File "/home/knorth55/ros/melodic/src/jsk-ros-pkg/jsk_3rdparty/switchbot_ros/scripts/switchbot.py", line 86, in update_device_list
    res = self.request()
  File "/home/knorth55/ros/melodic/src/jsk-ros-pkg/jsk_3rdparty/switchbot_ros/scripts/switchbot.py", line 38, in request
    headers={'Authorization': self.token}
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.switch-bot.com', port=443): Max retries exceeded with url: /v1.0/devices/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1be57af950>: Failed to establish a new connection: [Errno -2] Name or service not known',))
[switchbot_ros-2] process has died [pid 17546, exit code 1, cmd /home/knorth55/ros/melodic/src/jsk-ros-pkg/jsk_3rdparty/switchbot_ros/scripts/switchbot_ros_server.py __name:=switchbot_ros __log:=/home/knorth55/.ros/log/570d6c54-fa61-11eb-a4a4-0242fc465144/switchbot_ros-2.log].
log file: /home/knorth55/.ros/log/570d6c54-fa61-11eb-a4a4-0242fc465144/switchbot_ros-2*.log
^C[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done
```

**Comment by mqcmd196** [comment]
I see, maybe I have to get the exception of not connecting to the internet, I'll fix later,

**Comment by knorth55** [comment]
both adding `respawn` arg and catching `requests.exceptions.ConnectionEror` would be nice.

**Comment by mqcmd196** [comment]
Closed https://github.com/jsk-ros-pkg/jsk_3rdparty/pull/279 .

**Pull request closed without merging**
