### PR TITLE
[WIP] [bayesian_belief_networks] Fix basename mismatch problem

### PR DESCRIPTION
**Pull request by garaemon**
Hope it solves the issue.

```
[bayesian_belief_networks] -- Check for working C compiler: /usr/bin/cc -- works 
[bayesian_belief_networks] -- Detecting C compiler ABI info                     
[bayesian_belief_networks] -- Detecting C compiler ABI info - done              
[bayesian_belief_networks] -- Check for working CXX compiler: /usr/bin/c++      
[bayesian_belief_networks] -- Check for working CXX compiler: /usr/bin/c++ -- works 
[bayesian_belief_networks] -- Detecting CXX compiler ABI info                   
[bayesian_belief_networks] -- Detecting CXX compiler ABI info - done            
[bayesian_belief_networks] -- Using CATKIN_DEVEL_PREFIX: /workspace/ros/ws_jsk_3rdparty/devel 
[bayesian_belief_networks] -- Using CMAKE_PREFIX_PATH: /opt/ros/indigo          
[bayesian_belief_networks] -- This workspace overlays: /opt/ros/indigo          
[bayesian_belief_networks] -- Found PythonInterp: /usr/bin/python (found version "2.7.6") 
[bayesian_belief_networks] -- Using PYTHON_EXECUTABLE: /usr/bin/python          
[bayesian_belief_networks] -- Using Debian Python package layout                
[bayesian_belief_networks] -- Using empy: /usr/bin/empy                         
[bayesian_belief_networks] -- Using CATKIN_ENABLE_TESTING: ON                   
[bayesian_belief_networks] -- Call enable_testing()                             
[bayesian_belief_networks] -- Using CATKIN_TEST_RESULTS_DIR: /workspace/ros/ws_jsk_3rdparty/build/bayesian_belief_networks/test_results 
[bayesian_belief_networks] -- Looking for include file pthread.h                
[bayesian_belief_networks] -- Looking for include file pthread.h - found        
[bayesian_belief_networks] -- Looking for pthread_create                        
[bayesian_belief_networks] -- Looking for pthread_create - not found            
[bayesian_belief_networks] -- Looking for pthread_create in pthreads            
[bayesian_belief_networks] -- Looking for pthread_create in pthreads - not found 
[bayesian_belief_networks] -- Looking for pthread_create in pthread             
[bayesian_belief_networks] -- Looking for pthread_create in pthread - found     
[bayesian_belief_networks] -- Found Threads: TRUE                               
[bayesian_belief_networks] -- Found gtest sources under '/usr/src/gtest': gtests will be built 
[bayesian_belief_networks] -- Using Python nosetests: /usr/bin/nosetests-2.7    
[bayesian_belief_networks] -- catkin 0.6.14                                     
[bayesian_belief_networks] -- Using these message generators: gencpp;genlisp;genpy 
[bayesian_belief_networks] CMake Error at /opt/ros/indigo/share/catkin/cmake/catkin_python_setup.cmake:96 (message): 
[bayesian_belief_networks]   The package name 'bayesian_belief_networks' differs from the basename of 
[bayesian_belief_networks]   the path 'src' in project 'bayesian_belief_networks' 
[bayesian_belief_networks] Call Stack (most recent call first):                 
[bayesian_belief_networks]   CMakeLists.txt:6 (catkin_python_setup)             
[bayesian_belief_networks]                                                      
[bayesian_belief_networks] -- Configuring incomplete, errors occurred!          
[bayesian_belief_networks] See also "/workspace/ros/ws_jsk_3rdparty/build/bayesian_belief_networks/CMakeFiles/CMakeOutput.log". 
[bayesian_belief_networks] See also "/workspace/ros/ws_jsk_3rdparty/build/bayesian_belief_networks/CMakeFiles/CMakeError.log". 
[bayesian_belief_networks] <== '/workspace/ros/ws_jsk_3rdparty/build/bayesian_belief_networks/build_env.sh /usr/bin/cmake /workspace/ros/ws_jsk_3rdparty/src/jsk_3rdparty/bayesian_belief_networks -DCATKIN_DEVEL_PREFIX=/workspace/ros/ws_jsk_3rdparty/devel -DCMAKE_INSTALL_PREFIX=/workspace/ros/ws_jsk_3rdparty/install' failed with return code '1' 
```

### CODE REVIEW

**Comment by garaemon** [comment]
this patch is not correct

**Comment by garaemon** [comment]
@aginika Do you know how to fix it?

**Comment by garaemon** [comment]
https://github.com/ros/catkin/commit/fcd76e692ca927d491053f63b2c9dcfc300af83f
This patch?

**Comment by garaemon** [comment]
confirmed https://github.com/ros/catkin/commit/fcd76e692ca927d491053f63b2c9dcfc300af83f this patch mekes error

**Comment by garaemon** [comment]
If we change setup.py like this, we can complete compilation but 
sample program does not work.

this package is too tricky?

```diff
--- a/bayesian_belief_networks/setup.py
+++ b/bayesian_belief_networks/setup.py
@@ -19,7 +19,7 @@ else:
 
 d = generate_distutils_setup(
     packages=['bayesian','bayesian_belief_networks'],
-    package_dir={'': target_dir,'bayesian_belief_networks':'src'}
+    package_dir={'': target_dir,'':'src'}
     )

```

**Comment by garaemon** [comment]
a lot of times, julius cannot be compiled because of sourceforce unstable connection.

**Comment by dirk-thomas** [comment]
As you have discovered yourself due to a recent change in `catkin` a CMake error triggered which did not before. Actually before the build past but your Python code was not usable in the devel space.

The currently released version of this repo has a regression in Indigo (http://www.ros.org/debbuild/indigo.html?q=bayesian_belief_networks) as well as Jade since you haven't released a new version with this fix yet. But I want to point out that the current fix is inaccurate. The actual change was introduced into catkin in version 0.6.15. Therefore this patch should be modified to state:

    if StrictVersion("@CATKIN_VERSION@") >= StrictVersion("0.6.15"):

Please update this patch and then release new patch versions into Indigo and Jade.

**Comment by garaemon** [comment]
@dirk-thomas Thanks!

**Pull request merged**
