### PR TITLE
catkine aques_talk

### PR DESCRIPTION
**Pull request by k-okada**
@mqcmd196 please try this with your new robot, this does not require internet connection

### CODE REVIEW

**Comment by mqcmd196** [comment]
I tried to build jsk_3rd party, and when building aques, catkin returned error.

What I executed:
```bash
mkdir aques_ws/src -p
git clone https://github.com/jsk-ros-pkg/jsk_3rdparty.git
cd jsk_3rdparty/
git remote add k-okada https://github.com/k-okada/jsk_3rdparty.git
git fetch k-okada
git checkout -b aques k-okada/aques
source /opt/ros/melodic/setup.bash
cd ..
catkin build
```

Error:
```
$ catkin build
--------------------------------------------------------
Profile:                     default
Extending:          [cached] /opt/ros/melodic
Workspace:                   /home/tork/aques_ws
--------------------------------------------------------
Build Space:        [exists] /home/tork/aques_ws/build
Devel Space:        [exists] /home/tork/aques_ws/devel
Install Space:      [unused] /home/tork/aques_ws/install
Log Space:          [exists] /home/tork/aques_ws/logs
Source Space:       [exists] /home/tork/aques_ws/src
DESTDIR:            [unused] None
--------------------------------------------------------
Devel Space Layout:          linked
Install Space Layout:        None
--------------------------------------------------------
Additional CMake Args:       None
Additional Make Args:        None
Additional catkin Make Args: None
Internal Make Job Server:    True
Cache Job Environments:      False
--------------------------------------------------------
Whitelisted Packages:        None
Blacklisted Packages:        None
--------------------------------------------------------
Workspace configuration appears valid.
--------------------------------------------------------
[build] Found '29' packages in 0.0 seconds.                                                             
[build] Package table is up to date.                                                                    
Starting  >>> aques_talk                                                                                
Starting  >>> assimp_devel                                                                              
Starting  >>> bayesian_belief_networks                                                                  
Starting  >>> dialogflow_task_executive                                                                 
Starting  >>> downward                                                                                  
Starting  >>> ff                                                                                        
Starting  >>> ffha                                                                                      
Starting  >>> gdrive_ros                                                                                
________________________________________________________________________________________________________
Errors     << aques_talk:make /home/tork/aques_ws/logs/aques_talk/build.make.001.log                    
/usr/bin/ld: -lAquesTalk2 が見つかりません
collect2: error: ld returned 1 exit status
make[2]: *** [/home/tork/aques_ws/devel/.private/aques_talk/lib/aques_talk/SampleTalk] Error 1
make[1]: *** [CMakeFiles/SampleTalk.dir/all] Error 2
make: *** [all] Error 2
cd /home/tork/aques_ws/build/aques_talk; catkin build --get-env aques_talk | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -
........................................................................................................
Failed     << aques_talk:make                          [ Exited with code 2 ]                           
Failed    <<< aques_talk                               [ 0.2 seconds ]             
```

I already rosdep installed on another ws like this:
```bash
rosdep install --ignore-src --from-paths src -y -r
```

**Comment by 708yamaguchi** [comment]
I faced the same error.

**Comment by k-okada** [comment]
sorry, should be fixed in e47fcac2

**Comment by mqcmd196** [comment]
I launched the script as readme shows.
```
$ roslaunch aques_talk aques_talk.launch 
... logging to /home/tork/.ros/log/3874da42-295c-11eb-a054-f875a4b60e3f/roslaunch-oem-ThinkPad-T490-690.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://oem-ThinkPad-T490:45211/

SUMMARY
========

PARAMETERS
 * /rosdistro: melodic
 * /rosversion: 1.14.9

NODES
  /
    sound_play_jp (sound_play/soundplay_node.py)

auto-starting new master
process[master]: started with pid [712]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 3874da42-295c-11eb-a054-f875a4b60e3f
process[rosout-1]: started with pid [723]
started core service [/rosout]
process[sound_play_jp-2]: started with pid [726]
こんにちわ/home/tork/aques_ws/devel/lib/aques_talk/SampleTalk: error while loading shared libraries: libAquesTalk2.so.2: cannot open shared object file: No such file or directory
[ERROR] [1605676197.920187]: Sound synthesis failed. Is festival installed? Is a festival voice installed? Try running "rosdep satisfy sound_play|sh". Refer to http://wiki.ros.org/sound_play/Troubleshooting
[ERROR] [1605676197.921552]: Exception in callback: 'NoneType' object has no attribute 'command'
```
```
$ rostopic pub /robotsound_jp  sound_play/SoundRequest "{sound: -3, command: 1, volume: 10.0, arg: 'こん にちわ', arg2: ''}"
publishing and latching message. Press ctrl-C to terminate
```

**Comment by k-okada** [comment]
sorry, fixed again...

**Comment by mqcmd196** [comment]
It worked! Thanks a lot!!

**Comment by 708yamaguchi** [comment]
I can use aques_talk in fetch1075!
Thank you very much!

**Comment by knorth55** [comment]
Travis failed in `kinetic` + `i386`.
https://travis-ci.org/github/jsk-ros-pkg/jsk_3rdparty/jobs/745319351

```
_______________________________________________________________________________

Errors << aques_talk:make /home/travis/ros/ws_jsk_3rdparty/logs/aques_talk/build.make.000.log

/usr/bin/ld: skipping incompatible /home/travis/ros/ws_jsk_3rdparty/devel/.private/aques_talk/lib/libAquesTalk2.so when searching for -lAquesTalk2


/usr/bin/ld: cannot find -lAquesTalk2


collect2: error: ld returned 1 exit status


make[2]: *** [/home/travis/ros/ws_jsk_3rdparty/devel/.private/aques_talk/lib/aques_talk/SampleTalk] Error 1


make[1]: *** [CMakeFiles/SampleTalk.dir/all] Error 2


make: *** [all] Error 2


cd /home/travis/ros/ws_jsk_3rdparty/build/aques_talk; catkin build --get-env aques_talk | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -


...............................................................................

Failed << aques_talk:make                           [ Exited with code 2 ]
```

**Comment by 708yamaguchi** [comment]
@knorth55 
Thank you, I am working on https://github.com/k-okada/jsk_3rdparty/pull/3

**Comment by 708yamaguchi** [comment]
Travis passed ! :sob::sob::sob:

**Pull request merged**
