### PR TITLE
[google_cloud_texttospeech] Support multiple languages.

### PR DESCRIPTION
**Pull request by iory**
# What is this?

This PR enables multiple languages using `google_cloud_texttospeech`.
The demo code and video are as follows.

## demo step
First, launch the sound_play node.
```
$ roslaunch google_cloud_texttospeech google_cloud_texttospeech.launch
```

Users can use it as follows.
```
$ roseus
(load "package://pr2eus/speak.l")

(ros::roseus "multi_language_sample")

(speak "JSKへようこそ。" :lang "ja-JP-Wavenet-B" :wait t)
(speak "Welcome to JSK." :lang "en-US-Wavenet-A" :wait t)
(speak "欢迎来到 JSK" :lang "yue-HK-Standard-A" :wait t)
(speak "Willkommen bei JSK" :lang "da-DK-Wavenet-D" :wait t)
```

## video

https://user-images.githubusercontent.com/4690682/125367966-3489da00-e3b4-11eb-83d5-d31af230d98c.mp4

### CODE REVIEW

**Review by k-okada — CHANGES_REQUESTED** [review]
please update documentation. https://github.com/jsk-ros-pkg/jsk_3rdparty/blob/master/3rdparty/google_cloud_texttospeech/README.md

Will `client.say('Hello', voice='en')` work?

**Comment by iory** [comment]
Thank you for your comment.
I added the docs. Please check it.

> Will `client.say('Hello', voice='en')` work?

It works. This code not changes the default behaviour.
Details are in the following part.
https://github.com/jsk-ros-pkg/jsk_3rdparty/pull/269/files#diff-eae6b228234bee5fba1f7f9e62919bf189b3b6a545dbe0f2d0a33c88a2f20962R323-R334

**Review by knorth55 — APPROVED** [review]

**Comment by iory** [comment]
I added a sample code for roseus users.
https://github.com/jsk-ros-pkg/jsk_3rdparty/blob/32257786d43ad94d2016a6d9e054ea0ed474dbed/3rdparty/google_cloud_texttospeech/README.md#for-roseus-users

**Comment by k-okada** [comment]
> Will client.say('Hello', voice='en') work?


I see, how about something like
```
name, language_code = filter(lambda kv: e.replace('(','').replace(')',''), in kv[1], lower2original.items())[0]
```
This keeps backward compatible and also support `voice='de'`

BTW, Is `da-DK` Denmark? German is `de-DE`?

**Comment by k-okada** [comment]
what is the difference between `Standard` and `Wavenet` and why we use `Wavenet` as a default for `ja` and `en`.

**Comment by iory** [comment]
> This keeps backward compatible and also support voice='de'

Thank you for your comment. I modified code for `language_code` such as `ja`, `de`, `en` etc.
https://github.com/jsk-ros-pkg/jsk_3rdparty/pull/269/files#diff-eae6b228234bee5fba1f7f9e62919bf189b3b6a545dbe0f2d0a33c88a2f20962R310-R332

> BTW, Is da-DK Denmark? German is de-DE?

This is my mistake. I fixed it.

> what is the difference between Standard and Wavenet and why we use Wavenet as a default for ja and en.

WaveNet voices are higher quality voices rather than standard voices.

https://github.com/jsk-ros-pkg/jsk_3rdparty/pull/269/files#diff-b0302d3b5f0a638baa55d99afa75a22046e976b5ef28a195e3b63c26bb8034a3R48

**Comment by knorth55** [comment]
FYI:
>what is the difference between Standard and Wavenet and why we use Wavenet as a default for ja and en.

Pricing and quality are different.
https://cloud.google.com/text-to-speech/pricing

**Pull request merged**
