### PR TITLE
google_chat_ros/README.md: add troubleshooting

### PR DESCRIPTION
**Pull request by k-okada**
誰かに質問して答えをえたらドキュメントに反映させるというルールだったとおもうのでPRを作りました

Cc: @tkmtnt7000

### CODE REVIEW

**Review by tkmtnt7000 — APPROVED** [review]

**Comment by k-okada** [comment]
@tkmtnt7000 did this PR fix the problem with  fetch robot?

**Comment by tkmtnt7000** [comment]
Umm.. Fetch1075's date of expiry of pub/sub service has already been indefinite...
There may be something wrong with other parts.
スクリーンショット 2023-04-07 10 48 35

**Comment by tkmtnt7000** [comment]
Fetch15's chat bot is now working, but it seems that JSK-Fetch15's pub/sub service does not exist.

**Comment by tkmtnt7000** [comment]
@mqcmd196

**Comment by knorth55** [comment]
FYI: PR2 uses pub/sub and I didn't set the expiration date, so maybe it may be default.

**Comment by tkmtnt7000** [comment]
Thank you for information. I updated PR2's pub/sub to make the expiration date indefinite.

**Comment by tkmtnt7000** [comment]
I changed the setting to use application URL and Fetch1075 bot is now working!!
image

**Comment by tkmtnt7000** [comment]
連投して申し訳ないですが，結局chatを送ったときに連携させるアプリケーションを必ずdialogflowを介させるか，それとも別のノードに任せるかというところで，アプリのURLを選ぶのかcloud Pub/Subを選ぶのか変わるのかな，とおもいました．

**Comment by mqcmd196** [comment]
> I changed the setting to use application URL and Fetch1075 bot is now working!!
It is the correct solution on Fetch.

**Pull request merged**
