### PR TITLE
Google Chat ROS

### PR DESCRIPTION
**Pull request by mqcmd196**
Moved from https://github.com/jsk-ros-pkg/jsk_3rdparty/pull/290 and covered all functions of Google Chat API.

### CODE REVIEW

**Comment by mqcmd196** [comment]
Waiting for https://github.com/ros/rosdistro/pull/33017 being merged

**Comment by knorth55** [comment]
please check CI test results.

```
Compiling ./google_chat_ros/scripts/google_chat_ros_node.py ...
  File "./google_chat_ros/scripts/google_chat_ros_node.py", line 163
    def event_cb(self, event: dict, publish_topic=True):
                            ^
SyntaxError: invalid syntax
```

**Comment by knorth55** [comment]
please resolve the conflict.

**Comment by knorth55** [comment]
and can you tell me when I should review this PR?

**Comment by mqcmd196** [comment]
> please check CI test results.
> 
> Compiling ./google_chat_ros/scripts/google_chat_ros_node.py ...
>   File "./google_chat_ros/scripts/google_chat_ros_node.py", line 163
>     def event_cb(self, event: dict, publish_topic=True):
>                             ^
> SyntaxError: invalid syntax

Sorry, I removed type-hinting

**Comment by mqcmd196** [comment]
Sorry for being late. I'll request review when the test goes fine

**Review by knorth55 — APPROVED** [review]

**Comment by k-okada** [comment]
https://github.com/jsk-ros-pkg/jsk_3rdparty/pull/392 fixed test and merged. @mqcmd196 if you have more changes, pleae create new PR.

**Pull request closed without merging**
